---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2020-06-16-22:50:04
---

local BaseModel = require("Game.Core.Ioc.BaseModel")
---@class Game.Modules.Adventure.Model.AdventureModel : Game.Core.Ioc.BaseModel
---@field adventureService Game.Modules.Adventure.Service.AdventureService
local AdventureModel = class("AdventureModel",BaseModel)

function AdventureModel:Ctor()
    
end

return AdventureModel
