---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2020-07-27-23:09:36
---

local BaseController = require("Game.Core.BaseController")
---@class Game.Modules.Battle.Ctrl.BattleCtrl : Game.Core.BaseController
---@field New fun():Game.Modules.Battle.Ctrl.BattleCtrl
---@field battleModel Game.Modules.Battle.Model.BattleModel
---@field battleConfigModel Game.Modules.BattleConfig.Model.BattleConfigModel
---@field battleService Game.Modules.Battle.Service.BattleService
---@field battleConfigService Game.Modules.BattleConfig.Service.BattleConfigService
local BattleCtrl = class("Game.Modules.Battle.Ctrl.BattleCtrl",BaseController)

--重新播放战报
function BattleCtrl:ReplayReport()
    self.battleConfigService:GetBattleConfig(self.roleModel.roleId,self.battleConfigModel.battleType, Handler.New( function()
        self.battleModel.isReplayReport = true
        self.battleConfigModel.selectList = self.battleModel.report:GetCardList()
        self:EnterCheckPoint()
    end, self))
end

--正式进入Pve战斗
---@param selectList List | table<number, Game.Modules.Card.Vo.CardVo>
function BattleCtrl:StartPveBattle(selectList)
    --真实战斗
    self.battleService:StartBattle(
            self.roleModel.roleId,
            self.checkPointModel.currSection.checkPointData.chapter,
            self.checkPointModel.currSection.checkPointData.id,
            function()
                self.battleConfigModel.selectList = selectList
                self:EnterCheckPoint()
            end)
end

--进入关卡
function BattleCtrl:EnterCheckPoint()
    local checkPointData = CheckPointConfig.GetBattleSceneData(self.checkPointModel.currSection.checkPointData.id)
    self.battleModel.currBattleMode = BattleMode.PVE
    self.battleModel.currCheckPointData = checkPointData
    self.battleModel.battleSceneInfo = BattleSceneConfig.Get(checkPointData.battleScene)
    World.worldScene:EnterCheckPoint(checkPointData.id)
end

return BattleCtrl
