---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2019/1/19 0:21
---

local ListItemRenderer = require("Betel.UI.ListItemRenderer")
---@class Game.Modules.Array.View.ArrayCardItem: Betel.UI.ListItemRenderer
---@field select boolean
local ArrayCardItem = class("Game.Modules.Login.View.ServerItem",ListItemRenderer)

---@param gameObject UnityEngine.GameObject
function ArrayCardItem:Ctor(gameObject)
    ArrayCardItem.super.Ctor(self,gameObject)
end

---@param cardVo Game.Modules.Card.Vo.CardVo
function ArrayCardItem:UpdateItem(cardVo, index)
    ArrayCardItem.super.UpdateItem(self, cardVo, index)
    local frameImg = self.gameObject:GetImage()
    frameImg.sprite = Res.LoadSprite(RankFrameUrl[cardVo.cardInfo.rank])

    local iconImg = self.gameObject:GetImage("Icon")
    iconImg.sprite = Res.LoadSprite(cardVo.cardInfo.iconUrl)
    iconImg.gameObject:SetActive(true)
    --iconImg:SetNativeSize()

    local mask = self.gameObject:FindChild("Mask")
    if mask then mask:SetActive(self.select) end
    local mark = self.gameObject:FindChild("Mark")
    if mark then mark:SetActive(self.select) end

    local starBar = self.gameObject:FindChild("StarBar")
    self:SetStar(starBar, cardVo.cardInfo.star)
    --starBar:SetActive(cardVo.fragmentStoneNum == 0)

    local displayText = self.gameObject:GetText("Display")
    displayText.text = "Lv." .. cardVo.level
end

---@param starBar UnityEngine.GameObject
function ArrayCardItem:SetStar(starBar, starNum)
    for i = 1, starBar.transform.childCount do
        local starImg = starBar.transform:GetChild(i - 1).gameObject:GetImage()
        starImg.sprite = UITools.GetSprite(starImg.gameObject, i <= starNum and 1 or 0)
        starImg.gameObject:SetActive(i <= starNum)
    end
end

function ArrayCardItem:OnDestroy()

end

return ArrayCardItem