---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhengnan.
--- DateTime: 2019/5/7 10:33
---

local Convert = {}

local tmpVec3 = Vector3.New()
-- 帧频
local frameRate = Application.targetFrameRate
if frameRate == -1 then
    frameRate = 60
end

--- 时间转帧数
---@param time @ 秒
---@return number
function Convert.TimeToFrameNum(time)
    return math.floor(time * frameRate + 0.5)
end


---@param val any
function Convert.DefaultNumber(val)
    if val == nil then
        return 0
    else
        local num = tonumber(val)
        return num == nil and 0 or num
    end
end

--- 世界坐标转 UI 坐标
--- 返回两个值：UI 坐标（超出屏幕范围时，返回 ConvertUtil.HIDE_POS），以及 是否在屏幕范围内
---
--- local pos, inScreen = ConvertUtil.WorldToCanvasPoint(...)
---
---@param p Vector3 @ 事件坐标
---@param camera UnityEngine.Camera @ 镜头对象。默认：Camera.main
---@param cameraTra UnityEngine.Transform @ 镜头对应的 Transform。默认：Camera.main.transform
---@param bufVal number @ 缓冲范围。默认：0.1
---@return Vector3, boolean
function Convert.WorldToCanvasPoint(p, camera, cameraTra, bufVal)
    camera = camera or Camera.main
    cameraTra = cameraTra or camera.transform
    bufVal = bufVal or 0.1

    local cvp = camera:WorldToViewportPoint(p)
    local dir = (p - cameraTra.position).normalized
    local dot = Vector3.Dot(cameraTra.forward, dir)
    local inScreen = dot > 0 and cvp.x >= -bufVal and cvp.x <= 1 + bufVal and cvp.y >= -bufVal and cvp.y <= 1 + bufVal
    if inScreen then
        return Convert.WorldPosToCanvasPoint(p, camera), inScreen
    else
        return Vector3.New(-9999, -9999, -9999), inScreen
    end
end

---@param pos Vector3 @ 事件坐标
---@param camera UnityEngine.Camera @ 镜头对象。默认：Camera.main
function Convert.WorldPosToCanvasPoint(pos, camera)
    pos = camera:WorldToScreenPoint(pos);
    pos = vmgr.uiCanvas.worldCamera:ScreenToWorldPoint(pos);
    local s = vmgr.uiCanvas.transform.localScale;
    tmpVec3:Set(pos.x / s.x, pos.y / s.y, vmgr.uiCanvas.transform.anchoredPosition3D.z);
    return tmpVec3;
end

--世界坐标转化为UI的本地坐标
---@param worldPos UnityEngine.Vector3 世界坐标
---@param worldCamera UnityEngine.Camera
---@param uiCanvas UnityEngine.Canvas  UICanvas
---@param parentRect UnityEngine.RectTransform 父容器
---@return UnityEngine.Vector2
function Convert.WorldPosToCanvasLocalPosition(worldPos, worldCamera, uiCanvas, parentRect)
    parentRect = parentRect == nil and vmgr:GetUILayer(UILayer.LAYER_TOP).gameObject:GetRect() or parentRect
    local screenPos = worldCamera:WorldToScreenPoint(worldPos)
    screenPos = Vector2.New(screenPos.x,screenPos.y)
    local uiLocalPos = LuaHelper.ScreenToCanvasPoint(screenPos, uiCanvas, parentRect)
    return uiLocalPos
end

function Convert.GetColorByQuaity(quality)
    if quality == 1 then
        return Color.New(1,1,1,1)
    elseif quality == 2 then
        return Color.New(30/255,190/255,255/255,1)
    elseif quality == 3 then
        return Color.New(245/255,12/255,220/255,1)
    elseif quality == 4 then
        return Color.New(235/255,97/255,0/255,1)
    else
        return Color.New(0,0,0,1)
    end
end

function Convert.GetAttrName(attrType)
    if attrType == AttrType.Atk then
        return "攻击"
    elseif attrType == AttrType.Def then
        return "防御"
    elseif attrType == AttrType.Hp then
        return "血量"
    else
        return "error attrType"
    end
end


return Convert