---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhengnan.
--- DateTime: 2020/2/21 13:26
--- 网格战斗模式相关工具
---

local GridUtils = {}

--获得九宫格的具体坐标
---@param center UnityEngine.Vector3
---@param forward UnityEngine.Vector3
---@param right UnityEngine.Vector3
---@return table<number, UnityEngine.Vector3>
function GridUtils.GetNineGridPoints(center, forward, right, gridSize)
    gridSize = gridSize or 1
    local grid = {};
    grid[1] = center + forward * gridSize
    grid[2] = grid[1] + right * gridSize
    grid[3] = grid[1] + -right * gridSize
    grid[4] = center
    grid[5] = grid[4] + right * gridSize
    grid[6] = grid[4] + -right * gridSize
    grid[9] = center + -forward * gridSize
    grid[8] = grid[9] + right * gridSize
    grid[7] = grid[9] + -right * gridSize
    return grid
end

--获取可以攻击目标的点
---@param target UnityEngine.GameObject
---@param range number
---@return UnityEngine.Vector3
function GridUtils.GetTargetAttackPoint(target, range)
    return target.transform.position + target.transform.forward * range
end


--获取可以攻击目标的点
---@param gridSelectType GridSelectType
---@param attacker Game.Modules.World.Items.BattleUnit
---@return table<number, number>
function GridUtils.GetTargetCampAndGrids(gridSelectType, targetCamp, attacker)
    if attacker.layoutIndex == nil or  attacker.layoutIndex == 0 then
        print(123123)
    end
    local selectGrids
    local curColIndexs = LayoutIndex2Col[attacker.layoutIndex]
    local firstTarget = attacker.context.battleLayout:GetFirstGridByIndexs(targetCamp, curColIndexs)
    if not firstTarget then
        firstTarget = attacker.context.battleLayout:GetFirstGrid(targetCamp)
    end
    if gridSelectType == GridSelectType.Current then
        selectGrids = {}
        if firstTarget then
            table.insert(selectGrids, firstTarget.index)
        end
    elseif gridSelectType == GridSelectType.Col then
        selectGrids = curColIndexs
    elseif gridSelectType == GridSelectType.Row then
        selectGrids = {}
        if firstTarget then
            selectGrids = LayoutIndex2Row[firstTarget.index]
        end
    elseif gridSelectType == GridSelectType.All then
        selectGrids = LayoutMapAll
    elseif gridSelectType == GridSelectType.Friend_All then
        selectGrids = LayoutMapAll
    elseif gridSelectType == GridSelectType.Friend_Lowest then
        selectGrids = LayoutMapAll
    else
        logError("unknown select type " .. gridSelectType)
    end
    return selectGrids
end

return GridUtils