---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhengnan.
--- DateTime: 2020/2/21 13:26
--- 网格战斗模式相关工具
---

local GridUtils = {}

--获得九宫格的具体坐标
---@param center UnityEngine.Vector3
---@param forward UnityEngine.Vector3
---@param right UnityEngine.Vector3
---@return table<number, UnityEngine.Vector3>
function GridUtils.GetNineGridPoints(center, forward, right, gridSize)
    gridSize = gridSize or 1
    local grid = {};
    grid[1] = center + forward * gridSize
    grid[2] = grid[1] + right * gridSize
    grid[3] = grid[1] + -right * gridSize
    grid[4] = center
    grid[5] = grid[4] + right * gridSize
    grid[6] = grid[4] + -right * gridSize
    grid[9] = center + -forward * gridSize
    grid[8] = grid[9] + right * gridSize
    grid[7] = grid[9] + -right * gridSize
    return grid
end

--获取可以攻击目标的点
---@param target UnityEngine.GameObject
---@param range number
---@return UnityEngine.Vector3
function GridUtils.GetTargetAttackPoint(target, range)
    return target.transform.position + target.transform.forward * range
end


--获取可以攻击目标的点
---@param gridSelectType GridSelectType
---@param attacker Game.Modules.World.Items.BattleUnit
---@param camp Camp
---@return table<number, number>
function GridUtils.GetGrids(gridSelectType, camp, attacker)
    local curColIndexs = LayoutIndex2Col[attacker.layoutIndex]
    local firstTarget = attacker.context.battleLayout:GetFirstGridByIndexs(camp, curColIndexs)
    local rowIndexs = LayoutIndex2Row[firstTarget.index]
    if gridSelectType == GridSelectType.Current then
        return curColIndexs
    elseif gridSelectType == GridSelectType.Col then
        return curColIndexs
    elseif gridSelectType == GridSelectType.Current then
        return rowIndexs
    elseif gridSelectType == GridSelectType.All then
        return LayoutMapAll
    else
        return curColIndexs
    end
end

return GridUtils