---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhengnan.
--- DateTime: 2019/4/11 17:41
--- 层级管理
---

local Layers = {}

Layers.Layer = {
    Unknown                 = -1,
    Default                 = 0,
    UI                      = 5,
    SceneUI                 = 8,
    BattleItem              = 9,
    --Hero                    = 10,
    Building                = 11,
    Road                    = 12,
    Unwalk                  = 20,
}

Layers.Name = {
    Default                 = "Default",
    UI                      = "UI",
    SceneUI                 = "SceneUI",
    BattleItem              = "BattleItem",
    Building                = "Building",
    Road                    = "Road",
    Unwalk                  = "Unwalk",
}

---@param name string
function Layers.GetLayerInt(name)
    if Layers["_"..name] == nil then
        Layers["_"..name] = LayerMask.NameToLayer(name)
        --print("测试输出:".. name);
        --print("测试输出:".. LayerMask.NameToLayer(name));
    end
    return Layers["_"..name]
end

---@param layerNames table <number,string>
function Layers.GetLayerMaskByNames(layerNames)
    local layerMask = 0
    for i = 1, #layerNames do
        local layer = Layers.GetLayerInt(layerNames[i])
        layerMask = LuaHelper.Bit_Or(layerMask, LuaHelper.GetLayerMask(layer))
    end
    return layerMask
end

---@param layers table <number,number>
function Layers.GetLayerMask(layers)
    local layerMask = 0
    for i = 1, #layers do
        layerMask = LuaHelper.Bit_Or(layerMask, LuaHelper.GetLayerMask(layers[i]))
    end
    return layerMask
end
---@param parentObj UnityEngine.GameObject
---@param layer number
function Layers.SetLayer(parentObj,layer)
    if parentObj then
        parentObj.layer = layer
        local childList = parentObj:GetComponentsInChildren(typeof(UnityEngine.Transform), true);
        if childList.Length > 0 then
            for i = 0, childList.Length - 1 do
                local childTransform = childList[i]
                local childObj = childTransform.gameObject
                childObj.layer = layer
            end
        end
    end
    return parentObj
end

function Layers.UI()
    return Layers.GetLayerInt(Layers.Name.UI)
end

function Layers.SceneUI()
    return Layers.GetLayerInt(Layers.Name.SceneUI)
end

function Layers.BattleItem()
    return Layers.GetLayerInt(Layers.Name.BattleItem)
end

return Layers