---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2020-04-12-20:24:22
---

local AvatarVo = require("Game.Modules.World.Vo.AvatarVo")
---@class Game.Modules.Battle.Vo.BattleItemVo : Game.Modules.World.Vo.AvatarVo
---@field New fun():Game.Modules.Battle.Vo.BattleItemVo

local BattleItemVo = class("Game.Modules.Battle.Vo.BattleItemVo",AvatarVo)

function BattleItemVo:Ctor()
    
end

function BattleItemVo:Init(avatarName)
    BattleItemVo.super.Init(self, avatarName)
end

function BattleItemVo:Dispose()
    BattleItemVo.super.Dispose(self)
end

return BattleItemVo
