---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2020-04-12-20:24:22
---

local AvatarVo = require("Game.Modules.World.Vo.AvatarVo")
---@class Game.Modules.Battle.Vo.BattleItemVo : Game.Modules.World.Vo.AvatarVo
---@field New fun():Game.Modules.Battle.Vo.BattleItemVo
---@field level number
---@field camp Camp 阵营 所属阵营
---@field skills table<number, Game.Modules.Battle.Vo.SkillVo>
---@field curHp number
---@field maxHp number
local BattleItemVo = class("Game.Modules.Battle.Vo.BattleItemVo",AvatarVo)

function BattleItemVo:Ctor()
    
end

return BattleItemVo
