---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2020-04-12-20:24:22
---

local AvatarVo = require("Game.Modules.World.Vo.AvatarVo")
---@class Game.Modules.Battle.Vo.BattleUnitVo : Game.Modules.World.Vo.AvatarVo
---@field New fun():Game.Modules.Battle.Vo.BattleUnitVo
---@field battleUnitInfo BattleUnitInfo
local BattleUnitVo = class("Game.Modules.Battle.Vo.BattleUnitVo",AvatarVo)

function BattleUnitVo:Ctor()
    
end

function BattleUnitVo:Init(battleUnitName)
    self.battleUnitInfo = BattleUnitConfig.Get(battleUnitName)
    BattleUnitVo.super.Init(self, self.battleUnitInfo.avatarName)
    self.level = 0
    self.curHp = 0
    self.maxHp = 0
end

function BattleUnitVo:Dispose()
    BattleUnitVo.super.Dispose(self)
    self.battleUnitInfo = nil
    self.level = 0
    self.curHp = 0
    self.maxHp = 0
end

return BattleUnitVo
