---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2019/5/18 23:06
---

local SubScene = require('Game.Modules.World.Scenes.Core.SubScene')

---@class Game.Modules.World.Scenes.BattleScene : Game.Modules.World.Scenes.Core.SubScene
---@field battleSceneInfo BattleSceneInfo
local BattleScene = class("Game.Modules.World.Scenes.BattleScene",SubScene)

---@param subSceneInfo SceneInfo
---@param unityScene UnityEngine.SceneManagement.Scene
function BattleScene:Ctor(subSceneInfo, unityScene)
    BattleScene.super.Ctor(self, subSceneInfo, unityScene)
end

function BattleScene:OnInitialize()

end
---@param battleSceneInfo BattleSceneInfo
function BattleScene:InitScene(battleSceneInfo)
    BattleScene.super.InitScene(self, battleSceneInfo)
    self.battleSceneInfo = battleSceneInfo
    self:InitSubScene()
    self:Show()
    vmgr:LoadView(ViewConfig.Battle)
end

---@return UnityEngine.GameObject
function BattleScene:GetLightObj()
    if self.lightObj == nil then
        local lightObj = self:FindRootObjInSubScene("Directional Light")
        if isnull(lightObj) then
            logError(string.format("This scene [%s]'s Light must named with 'Directional Light' and set to root", self.subLevelName))
        end
        self.lightObj = lightObj:FindChild(self.battleSceneInfo.light)
    end
    return self.lightObj
end

function BattleScene:OnExitScene()
    vmgr:UnloadView(ViewConfig.Battle)
end

return BattleScene