---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2018/8/14 22:07
---

local BaseScene = require('Game.Modules.World.Scenes.BaseScene')
---@class Game.Modules.World.Scenes.LoadingScene : Modules.World.Scenes.BaseScene
local LoadingScene = class("LoadingScene",BaseScene)

function LoadingScene:Ctor()
    BaseScene.Ctor(self)
end

function LoadingScene:OnEnterScene()
    vmgr:LoadView(ViewConfig.Loading)
    --vmgr:LoadView(ViewConfig.NewbieWelcome)
end

function LoadingScene:OnExitScene()
    vmgr:UnloadView(ViewConfig.Loading)
end
return LoadingScene