---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2018/6/30 0:02
---

local BaseScene = require('Game.Modules.World.Scenes.BaseScene')
---@class Game.Modules.World.Scenes.LoginScene : Modules.World.Scenes.BaseScene
local LoginScene = class("LoginScene",BaseScene)

function LoginScene:Ctor()
    BaseScene.Ctor(self)
end

function LoginScene:OnEnterScene()
    vmgr:LoadView(ViewConfig.LoginScene)
end

function LoginScene:OnExitScene()
    vmgr:UnloadView(ViewConfig.LoginScene)
end
return LoginScene