---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2018/6/30 0:02
---

local MainScene = require('Game.Modules.World.Scenes.Core.MainScene')
---@class Game.Modules.World.Scenes.LoginScene : Game.Modules.World.Scenes.Core.MainScene
local LoginScene = class("LoginScene",MainScene)

---@param sceneInfo SceneInfo
---@param unityScene UnityEngine.SceneManagement.Scene
function LoginScene:Ctor(sceneInfo, unityScene)
    LoginScene.super.Ctor(self, sceneInfo, unityScene)
end

function LoginScene:OnEnterScene()
    vmgr:LoadView(ViewConfig.LoginScene)
end

function LoginScene:OnExitScene()
    vmgr:UnloadView(ViewConfig.LoginScene)
end
return LoginScene