---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ruizhan911.
--- DateTime: 2019/2/5 23:12
---


local BaseScene = require('Game.Modules.World.Scenes.BaseScene')
---@class Game.Modules.World.Scenes.Room_HJScene : Modules.World.Scenes.BaseScene
local Room_HJScene = class("Room_HJScene",BaseScene)

function Room_HJScene:Ctor()
    BaseScene.Ctor(self)
end

function Room_HJScene:OnEnterScene()
    vmgr:LoadView(ViewConfig.HongJianScene)
end

return Room_HJScene
