---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhengnan.
--- DateTime: 2020-04-04 23:34
---

local MainScene = require('Game.Modules.World.Scenes.Core.MainScene')

---@class Game.Modules.World.Scenes.WorldScene : Game.Modules.World.Scenes.Core.MainScene
local WorldScene = class("LobbyScene",MainScene)

---@param sceneInfo SceneInfo
---@param unityScene UnityEngine.SceneManagement.Scene
function WorldScene:Ctor(sceneInfo, unityScene)
    WorldScene.super.Ctor(self, sceneInfo, unityScene)
    World.worldScene = self
end

function WorldScene:OnEnterScene()
    --vmgr:LoadView(ViewConfig.NewbieWelcome)

    CheckPointConfig.Init()

    self:EnterLobby()
end

--进入关卡战斗
function WorldScene:EnterCheckPoint(checkPointName)
    local checkPointData = CheckPointConfig.GetBattleSceneData(checkPointName)
    local battleSceneInfo = BattleSceneConfig.Get(checkPointData.battleScene)
    self:EnterSubScene(battleSceneInfo.level,function(subScene)
        subScene:InitScene(battleSceneInfo)
    end)
end

function WorldScene:OnExitScene()

end

function WorldScene:EnterLobby()
    self:EnterSubScene("Lobby")
end

return WorldScene