---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhengnan.
--- DateTime: 2020-04-04 23:34
---

local BaseScene = require('Game.Modules.World.Scenes.BaseScene')
---@class Game.Modules.World.Scenes.WorldScene : Game.Modules.World.Scenes.BaseScene
local WorldScene = class("LobbyScene",BaseScene)

function WorldScene:Ctor()
    BaseScene.Ctor(self)
end

function WorldScene:OnEnterScene()
    --vmgr:LoadView(ViewConfig.NewbieWelcome)
    Framework.Ticker.Launch()
    FastBehavior.StateMachineManager.GetInstance():Init()
    FastBehavior.StateMachineManager.GetInstance().StateActionTimeout = 100
end

function WorldScene:OnExitScene()
end

return WorldScene