---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2019-05-18-23:22:49
---

local WeaponNo1 = require("Game.Modules.Battle.Weapon.WeaponNo1")
local WeaponDefault = require("Game.Modules.Battle.Weapon.WeaponDefault")
local BaseMediator = require("Game.Core.Ioc.BaseMediator")

---@class Game.Modules.Battle.View.BattleMdr : Game.Core.Ioc.BaseMediator
---@field battleModel Game.Modules.Battle.Model.BattleModel
---@field battleService Game.Modules.Battle.Service.BattleService
---@field ecsWorld Game.ECSWorld
---@field viewPortRect UnityEngine.Rect
---@field startTime number
---@field enemyBornIntervalTime number
local BattleMdr = class("BattleMdr", BaseMediator)

function BattleMdr:OnInit()
    World.root = GameObject.New("[World]")
    self.ecsWorld = GameObject.Find("BootStrap"):GetComponent(typeof(Game.ECSWorld))
    self.ecsWorld:Launch()

    self.viewPortRect = self.ecsWorld.cornerRect
    log(self.viewPortRect.x)

    self.startTime = Time.time
    self.enemyBornIntervalTime = 1
    self:CreateHeroAirplane()

    vmgr:LoadView(ViewConfig.BattleInfo)
    vmgr:LoadView(ViewConfig.Joystick)
end

function BattleMdr:CreateHeroAirplane()
    local mesh = Res.LoadMesh("Models/StarSparrow/Models/StarSparrow1.mesh")
    local material = Res.LoadMaterial("Models/StarSparrow/Materials/StarSparrow1.mat")
    local airplaneInfo = Game.AirplaneInfo.New(mesh, material, LayerMask.NameToLayer("Hero"))
    local size = Vector2.New(0.5, 1)
    airplaneInfo.BornPos = Vector3.New(
            0,
            0,
            self.viewPortRect.y - self.viewPortRect.height + size.y
    )
    airplaneInfo.ShootIntervalTime = 10 * FRAME_TIME
    airplaneInfo.Size = size
    airplaneInfo.MoveSpeed = self.ecsWorld.MoveSpeed
    airplaneInfo.Scale = Vector3.New(0.5, 0.5, 0.5)
    airplaneInfo.MaxHp = math.random(50, 100)
    airplaneInfo.BoxSize = Vector3.New(0.5, 0.1, 0.5)
    self.ecsWorld:CreateAirplane(airplaneInfo)

    self:RegisterWeapon("Game.Modules.Battle.Weapon.WeaponDefault")
    self:RegisterWeapon("Game.Modules.Battle.Weapon.WeaponNo1")
    self:RegisterWeapon("Game.Modules.Battle.Weapon.WeaponNo2")
end

--注册武器
---@param weaponClass string
function BattleMdr:RegisterWeapon(weaponClass)
    require(weaponClass).New(self.ecsWorld)
end

function BattleMdr:CreateEnemyAirplane()
    local mesh = Res.LoadMesh("Models/StarSparrow/Models/StarSparrow1.mesh")
    local material = Res.LoadMaterial("Models/StarSparrow/Materials/StarSparrow1.mat")
    local airplaneInfo = Game.AirplaneInfo.New(mesh, material, LayerMask.NameToLayer("Enemy"))
    local scale = 0.3 + math.random() * 0.2
    local size = Vector2.New(1, 1) * scale
    --随机出生点
    airplaneInfo.BornPos = Vector3.New(
            math.random(self.viewPortRect.x + size.x, self.viewPortRect.x + self.viewPortRect.width - size.x),
            0,
            self.viewPortRect.y + size.y
    )
    airplaneInfo.Size = size
    airplaneInfo.MoveSpeed = 3 + math.random(0.01, 3.01)
    airplaneInfo.RotationY = 180
    airplaneInfo.Scale = Vector3.New(scale, 0.1, scale)
    airplaneInfo.BulletSpeed = 30
    airplaneInfo.BulletScale = Vector3.New(0.4, 0.5, 1)
    airplaneInfo.ShootOffset = 0.7
    airplaneInfo.LifeTime = 4
    airplaneInfo.MaxHp = math.random(20, 100)
    airplaneInfo.BoxSize = Vector3.New(1.5, 0.1, 1) * scale
    airplaneInfo.Damage = 10
    airplaneInfo.ShadowCastingMode = UnityEngine.Rendering.ShadowCastingMode.On
    airplaneInfo.ReceiveShadows = false
    self.ecsWorld:CreateAirplane(airplaneInfo)
end

function BattleMdr:Update()
    --每隔一段时间产生一架敌机
    if Time.time - self.startTime > self.enemyBornIntervalTime then
        Game.ECSWorld.Instance:StartGame()
        self.startTime = Time.time
        self.enemyBornIntervalTime = math.random(0.5, 1)
        self:CreateEnemyAirplane()
    end
end

return BattleMdr
