---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2020/6/29 21:24
---

local ListItemRenderer = require("Betel.UI.ListItemRenderer")
---@class Game.Modules.Battle.View.BattleHeroItem: Betel.UI.ListItemRenderer
---@field battleUnitVo Game.Modules.Battle.Vo.BattleUnitVo
local BattleHeroItem = class("Game.Modules.Battle.View.BattleHeroItem",ListItemRenderer)

---@param gameObject UnityEngine.GameObject
function BattleHeroItem:Ctor(gameObject)
    BattleHeroItem.super.Ctor(self,gameObject)
end

---@param battleUnit Game.Modules.World.Items.BattleUnit
function BattleHeroItem:UpdateItem(battleUnit, index)
    self.battleUnitVo = battleUnit.battleUnitVo
    local cardVo = battleUnit.ownerCardVo
    BattleHeroItem.super.UpdateItem(self, self.battleUnitVo, index)
    self.shan = self.gameObject:GetImage("Shan")
    self.shan.gameObject:SetActive(false)

    local frameImg = self.gameObject:GetImage("Frame")
    frameImg.sprite = Res.LoadSprite(RankFrameUrl[cardVo.cardInfo.rank])

    local iconImg = self.gameObject:GetImage("Icon")
    iconImg.sprite = Res.LoadSprite(cardVo.cardInfo.iconUrl)
    iconImg.gameObject:SetActive(true)
    --iconImg:SetNativeSize()

    local starBar = self.gameObject:FindChild("StarBar")
    self:SetStar(starBar, cardVo.cardInfo.star)
    --starBar:SetActive(cardVo.fragmentStoneNum == 0)

    local displayText = self.gameObject:GetText("Display")
    displayText.text = "Lv." .. cardVo.level

    self.hpBar = self.gameObject:GetSlider("SliderHP")
    self.pwBar = self.gameObject:GetSlider("SliderPW")
    self.hpBar.minValue = 0
    self.hpBar.maxValue = self.battleUnitVo.maxHp
    self.pwBar.maxValue = 0
    self.pwBar.maxValue = self.battleUnitVo.maxTp
end

function BattleHeroItem:SetShan(shan)
    if shan then
        if self.shanTween == nil then
            self.shan.gameObject:SetActive(true)
            self.shan.transform.localScale = Vector3.one
            self.shan.color = Color.New(1,1,1,0.5)
            self.shanTween = self:CreateSequence()
            self.shanTween:Append(self.shan.transform:DOScale(Vector3.New(1.1,1.1,1.1), 0.3))
            self.shanTween:Join(self.shan:DOFade(1, 0.3))
            self.shanTween:Append(self.shan.transform:DOScale(Vector3.one, 0.3))
            self.shanTween:Join(self.shan:DOFade(0.5, 0.3))
            self.shanTween:SetLoops(-1, DOTween_Enum.LoopType.Yoyo)
        end
    else
        if self.shanTween then
            self.shan.transform.localScale = Vector3.one
            self.shan.gameObject:SetActive(false)
            self.shan.transform:DOPause()
            self.shan.transform:DOKill()
            self.shanTween:Kill()
            self.shanTween = nil
        end
    end
end

function BattleHeroItem:Update()
    if self.battleUnitVo then
        self.hpBar.value = self.battleUnitVo.curHp
        self.pwBar.value = self.battleUnitVo.curTp
        if self.battleUnitVo.curTp >= self.battleUnitVo.maxTp then
            self:SetShan(true)
        else
            self:SetShan(false)
        end
    end
end

---@param starBar UnityEngine.GameObject
function BattleHeroItem:SetStar(starBar, starNum)
    for i = 1, starBar.transform.childCount do
        local starImg = starBar.transform:GetChild(i - 1).gameObject:GetImage()
        starImg.sprite = UITools.GetSprite(starImg.gameObject, i <= starNum and 1 or 0)
        starImg.gameObject:SetActive(i <= starNum)
    end
end

function BattleHeroItem:OnDestroy()
    if self.shanTween then
        self.shanTween:Kill()
        self.shanTween = nil
    end
end

return BattleHeroItem