---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2020-06-28-23:55:51
---

local BaseMediator = require("Game.Core.Ioc.BaseMediator")
---@class Game.Modules.Battle.View.BattleResultMdr : Game.Core.Ioc.BaseMediator
---@field battleModel Game.Modules.Battle.Model.BattleModel
---@field battleService Game.Modules.Battle.Service.BattleService
local BattleResultMdr = class("Game.Modules.Battle.View.BattleResultMdr",BaseMediator)

function BattleResultMdr:OnInit()
    self.gameObject:GetText("Panel/Title/Text").text = self.battleModel.battleResult and "战斗胜利" or "战斗失败"
end

function BattleResultMdr:On_Click_BtnDone()
    self:Unload()
    World.worldScene:EnterLobby()--再次进入大厅
end

return BattleResultMdr
