---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2020-04-24-00:26:21
---

local BaseMediator = require("Game.Core.Ioc.BaseMediator")
---@class Game.Modules.Battle.View.BattleEditorMdr : Game.Core.Ioc.BaseMediator
---@field battleModel Game.Modules.Battle.Model.BattleModel
---@field battleService Game.Modules.Battle.Service.BattleService
local BattleEditorMdr = class("Game.Modules.Battle.View.BattleEditorMdr",BaseMediator)

function BattleEditorMdr:OnInit()
    self.context = self.battleModel.currentContext
end

function BattleEditorMdr:On_Click_Btn_Start()

end

return BattleEditorMdr
