---
--- Generated by Tools
--- Created by zhengnan.
--- DateTime: 2020-03-03-13:42:04
--- 常规场景战斗模块
---


local BattleLayout = require("Game.Modules.Battle.Layouts.BattleLayout")
local BattleEvents = require("Game.Modules.Battle.Events.BattleEvents")
local WorldContext = require("Game.Modules.World.Contexts.WorldContext")
local BaseMediator = require("Game.Core.Ioc.BaseMediator")
---@class Game.Modules.Battle.View.BattleMdrBase : Game.Core.Ioc.BaseMediator
---@field battleModel Game.Modules.Battle.Model.BattleModel
---@field playerModel Game.Modules.Player.Model.PlayerModel
---@field arrayModel Game.Modules.Array.Model.ArrayModel
---@field battleService Game.Modules.Battle.Service.BattleService
---@field context WorldContext
---@field battleSceneInfo BattleSceneInfo --战斗场景信息
local BattleMdrBase = class("Module.Battle.View.BattleMdrBase",BaseMediator)

function BattleMdrBase:OnInit()
    self.battleModel.playerVo = self.playerModel.myPlayerVo;
    self.battleSceneInfo = self.battleModel.battleSceneInfo

    self:InitCheckPointData()   --初始化关卡数据
    self:InitBattleMode()       --初始化战斗模式
    self:InitObjectPool()       --初始化对象池
    self:InitLayoutData()       --初始化布局
    self:StartBattle()          --开始战斗

    --BattleEvents.Dispatch({type = BattleEvents.BattleStart, checkPointData = self.checkPointData})
end

function BattleMdrBase:RegisterListeners()

end

--初始化关卡数据
function BattleMdrBase:InitCheckPointData()
    log("Init Battle Scene" .. self.battleSceneInfo.id)
    self.context = WorldContext.New(self.battleModel.currBattleMode)
    self.battleModel.currentContext = self.context
    self.context.checkPointData = self.battleModel.currCheckPointData
    self.context.battleSceneInfo = self.battleSceneInfo
    self.context.currSubScene = World.worldScene.currSubScene
    self.context:CreateAvatarRoot()
    --A*
    --self.context.grid = self.context.currSubScene:FindRootObjInSubScene("A*"):GetComponent(typeof(AStar.Grid))
    --self.context.gridGap = self.context.grid.nodeRadius * 2
    --self.context.grid.gameObject:SetActive(true)
end


--初始化对象池
function BattleMdrBase:InitObjectPool()

end

function BattleMdrBase:InitLayoutData()
    local obstructs = self.context.currSubScene:FindRootObjInSubScene("Obstructs")
    if obstructs then
        obstructs:SetActive(false)
    end
    local layoutPrefab = Instantiate(self.battleSceneInfo.layoutPrefabUrl)
    --布局
    local areaPointObj = layoutPrefab:FindChild(self.battleSceneInfo.layoutPoints)
    self.context.battleLayout = BattleLayout.New(self.context, areaPointObj)--创建布局
end

--初始化战斗模式
function BattleMdrBase:InitBattleMode()

end

function BattleMdrBase:StartBattle()

end

function BattleMdrBase:OnRemove()
    BattleMdrBase.super.OnRemove(self)
    --释放上下文
    self.context:Dispose()
    self.battleModel:Clear()
    BattleEvents.Dispatch(BattleEvents.BattleEnd)
end

return BattleMdrBase
