---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2020/4/10 23:23
--- 战斗上下文
---

---@class BattleContext
local BattleContext = class("BattleContext")

return BattleContext
