---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2020-06-01-22:42:27
---

local BaseMediator = require("Game.Core.Ioc.BaseMediator")
---@class Game.Modules.Lobby.View.LobbyMdr : Game.Core.Ioc.BaseMediator
---@field lobbyModel Game.Modules.Lobby.Model.LobbyModel
---@field roleModel Game.Modules.Role.Model.RoleModel
---@field lobbyService Game.Modules.Lobby.Service.LobbyService
---@field cardService Game.Modules.Card.Service.CardService
local LobbyMdr = class("Game.Modules.Lobby.View.LobbyMdr",BaseMediator)

function LobbyMdr:OnInit()
    self.cardService:getCardList(self.roleModel.roleInfo.id, self.OnCardList)
    vmgr:LoadView(ViewConfig.RoleInfo)
    vmgr:LoadView(ViewConfig.Navigation)
end

function LobbyMdr:OnCardList(data)

end

return LobbyMdr
