---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2020-04-10-22:53:29
---

---@class NavigationInfo
---@field label string
---@field views List | table<number, Game.Manager.ViewInfo>

local BaseMediator = require("Game.Core.Ioc.BaseMediator")
---@class Game.Modules.Lobby.View.NavigationMdr : Game.Core.Ioc.BaseMediator
---@field lobbyModel Game.Modules.Lobby.Model.LobbyModel
---@field lobbyService Game.Modules.Lobby.Service.LobbyService
---@field btns List | table<number, UnityEngine.UI.Toggle>
---@field currSelectTabIndex number
local NavigationMdr = class("Game.Modules.Lobby.View.NavigationMdr",BaseMediator)

function NavigationMdr:Ctor()
    NavigationMdr.super.Ctor(self)
    self.layer = UILayer.LAYER_FLOAT
end

function NavigationMdr:OnInit()
    NetModal.Show()
    navigation:Init()
    navigation:NavigateTo(self.lobbyModel.currNavPage, function()
        NetModal.Hide()
    end)
    self.btns = List.New()
    self.toggleGroup = self.gameObject:GetToggleGroup("Bar")
    for i = 1, #navigation.navigationPages do
        local toggle = self.gameObject:GetToggle("Bar/Toggle" .. i)
        toggle.isOn = self.lobbyModel.currNavPage == i
        self.gameObject:GetText("Bar/Toggle" .. i .. "/Label").text = navigation.navigationPages[i].label
        self.btns:Add(toggle.gameObject)
        self:AddClickEventListener(toggle.gameObject, self.OnTabClick)
    end
end

---@param event UnityEngine.EventSystems.PointerEventData
function NavigationMdr:OnTabClick(event)
    local index = self.btns:IndexOf(event.pointerPress)
    if index >= 1 then
        if self.lobbyModel.currNavPage == index then
            return
        end
        NetModal.Show()
        navigation:NavigateTo(index, function()
            NetModal.Hide()
        end)
        self.lobbyModel.currNavPage = index
        --print("Click " .. ButtonLabels[index])
    end
end

return NavigationMdr
