---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhengnan.
--- DateTime: 2019/9/21 14:28
---

local LuaObject = require("Betel.LuaObject")

---@class Game.Modules.Battle.Weapon.WeaponBase : Betel.LuaObject
---@field ecsWorld Game.ECSWorld
---@field weaponList table<number, Game.Weapon>
---@field levelIndexs table<number, table<number, number>>
local WeaponBase = class("Game.Modules.Battle.Weapon.WeaponBase",LuaObject)

---@param ecsWorld Game.ECSWorld
function WeaponBase:Ctor(ecsWorld)
    self.ecsWorld = ecsWorld
    self.weaponList = List.New()
end

---@return Game.WeaponInfo
function WeaponBase:CreateWeaponInfo(no, level)
    local weaponInfo = Game.WeaponInfo.New()
    weaponInfo.No = no
    weaponInfo.Level = level
    weaponInfo.Damage = math.random(10, 30)
    weaponInfo.ShootOffset = 0.7
    weaponInfo.BulletSpeed = 30
    weaponInfo.BulletScale = Vector3.New(0.3, 1, 1)
    return weaponInfo
end

---@param weapon Game.Weapon
function WeaponBase:AddWeapon(weapon)
    self.weaponList:Add(weapon)
end

function WeaponBase:SetWeaponLevel(level)
    for i = 1, #self.levelIndexs do
        if i <= level then
            self:SetWeaponActive(self.levelIndexs[i], true)
        else
            self:SetWeaponActive(self.levelIndexs[i], false)
        end
    end
end

---@param levelIndex table<number, number>
---@param active boolean
function WeaponBase:SetWeaponActive(levelIndex, active)
    for i = 1, #levelIndex do
        print("SetWeaponActive1 " .. tostring(self.weaponList[levelIndex[i]].Active))
        self.weaponList[levelIndex[i]].Active = active
        print("SetWeaponActive2 " .. tostring(self.weaponList[levelIndex[i]].Active))
    end
end

return WeaponBase