---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhengnan.
--- DateTime: 2019/9/21 14:28
---

local WeaponBase = require("Game.Modules.Battle.Weapon.WeaponBase")

---@class Game.Modules.Battle.Weapon.WeaponNo2 : Game.Modules.Battle.Weapon.WeaponBase
---@field New fun(ecsWorld:Game.ECSWorld)
local WeaponNo2 = class("Game.Modules.Battle.Weapon.WeaponNo2", WeaponBase)



---@param ecsWorld Game.ECSWorld
function WeaponNo2:Ctor(ecsWorld)
    WeaponNo2.super.Ctor(self, ecsWorld)

    local weaponInfo = self:CreateWeaponInfo()
    weaponInfo.Level = 1
    weaponInfo.SkinId = 2
    weaponInfo.BulletScale = Vector3.New(1.3, 1, 1)
    self:AddWeapon(ecsWorld:CreateWeapon(weaponInfo))

    weaponInfo.Level = 2
    weaponInfo.SkinId = 3
    weaponInfo.BulletScale = Vector3.New(1.6, 1, 1)
    self:AddWeapon(ecsWorld:CreateWeapon(weaponInfo))

    weaponInfo.Level = 3
    weaponInfo.SkinId = 3
    weaponInfo.BulletScale = Vector3.New(1.8, 1, 1)
    self:AddWeapon(ecsWorld:CreateWeapon(weaponInfo))

    weaponInfo.Level = 4
    weaponInfo.SkinId = 4
    weaponInfo.BulletScale = Vector3.New(1.5, 1, 1)
    self:AddWeapon(ecsWorld:CreateWeapon(weaponInfo))

    weaponInfo.Level = 5
    weaponInfo.SkinId = 4
    weaponInfo.BulletScale = Vector3.New(2, 1, 1)
    self:AddWeapon(ecsWorld:CreateWeapon(weaponInfo))
end

---@return Game.WeaponInfo
function WeaponNo2:CreateWeaponInfo()
    local weaponInfo = Game.WeaponInfo.New()
    weaponInfo.No = 2
    weaponInfo.Damage = 30
    weaponInfo.ShootOffset = Vector3.New(0, 0, 0.7)
    weaponInfo.BulletSpeed = self.ecsWorld.BulletSpeed
    weaponInfo.BulletEuler = Vector3.New(90, 180, 0)
    weaponInfo.ShootDir = Vector3.New(0, 0, 1)
    weaponInfo.BoxSize = Vector3.New(0.4, 0.1, 0.3)
    weaponInfo.BulletGap = 0

    return weaponInfo
end


return WeaponNo2