---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhengnan.
--- DateTime: 2019/9/21 14:28
---

local WeaponBase = require("Game.Modules.Battle.Weapon.WeaponBase")

---@class Game.Modules.Battle.Weapon.WeaponNo1 : Game.Modules.Battle.Weapon.WeaponBase
---@field New fun(ecsWorld:Game.ECSWorld)
local WeaponNo1 = class("Game.Modules.Battle.Weapon.WeaponNo1", WeaponBase)

local A = 90 / 16
local X = 1 / 16
local G = 0.16

---@param ecsWorld Game.ECSWorld
function WeaponNo1:Ctor(ecsWorld)
    WeaponNo1.super.Ctor(self, ecsWorld)

    local weaponInfo = self:CreateWeaponInfo()

    --1级武器
    weaponInfo.Level = 1
    self:SetWeapon(weaponInfo, -1, 1, 1)
    self:SetWeapon(weaponInfo, 1, 1, 1)

    weaponInfo.Level = 2
    self:SetWeapon(weaponInfo, -1, 1, 2)
    self:SetWeapon(weaponInfo, 1, 1, 2)

    weaponInfo.Level = 3
    self:SetWeapon(weaponInfo, -1, 2, 3)
    self:SetWeapon(weaponInfo, 1, 2, 3)

    weaponInfo.Level = 4
    self:SetWeapon(weaponInfo, -1, 2, 4)
    self:SetWeapon(weaponInfo, 1, 2, 4)

    weaponInfo.Level = 5
    self:SetWeapon(weaponInfo, -1, 1, 3)
    self:SetWeapon(weaponInfo, 1, 1, 3)
    self:SetWeapon(weaponInfo, -1, 2, 5)
    self:SetWeapon(weaponInfo, 1, 2, 5)
    ----二级武器
    --weaponInfo.Level = 2
    --weaponInfo.BulletEuler = Vector3.New(90, 157.5, 0)
    --weaponInfo.ShootDir = Vector3.New(-0.25, 0, 0.5)
    --weaponInfo.BulletGap = -0.5
    --self:AddWeapon(ecsWorld:CreateWeapon(weaponInfo))
    --weaponInfo.BulletGap = -0.7
    --self:AddWeapon(ecsWorld:CreateWeapon(weaponInfo))
    --
    --weaponInfo.BulletEuler = Vector3.New(90, 202.5, 0)
    --weaponInfo.ShootDir = Vector3.New(0.25, 0, 0.5)
    --weaponInfo.BulletGap = 0.5
    --self:AddWeapon(ecsWorld:CreateWeapon(weaponInfo))
    --weaponInfo.BulletGap = 0.7
    --self:AddWeapon(ecsWorld:CreateWeapon(weaponInfo))
    --
    ----三级武器
    --weaponInfo.Level = 3
    --weaponInfo.BulletEuler = Vector3.New(90, 157.5, 0)
    --weaponInfo.ShootDir = Vector3.New(-0.25, 0, 0.5)
    --weaponInfo.BulletGap = -0.5
    --self:AddWeapon(ecsWorld:CreateWeapon(weaponInfo))
    --weaponInfo.BulletGap = -0.7
    --self:AddWeapon(ecsWorld:CreateWeapon(weaponInfo))
    --
    --weaponInfo.BulletEuler = Vector3.New(90, 202.5, 0)
    --weaponInfo.ShootDir = Vector3.New(0.25, 0, 0.5)
    --weaponInfo.BulletGap = 0.5
    --self:AddWeapon(ecsWorld:CreateWeapon(weaponInfo))
    --weaponInfo.BulletGap = 0.7
    --self:AddWeapon(ecsWorld:CreateWeapon(weaponInfo))
end

---@param weaponInfo Game.WeaponInfo
function WeaponNo1:SetWeapon(weaponInfo, dir, angleNum, gapNum)
    weaponInfo.BulletEuler = Vector3.New(90, 180 + dir * angleNum * A, 0)
    weaponInfo.ShootDir = Vector3.New(dir * angleNum * X, 0, 0.5)
    weaponInfo.BulletGap = dir * G * gapNum
    self:AddWeapon(self.ecsWorld:CreateWeapon(weaponInfo))
end

---@return Game.WeaponInfo
function WeaponNo1:CreateWeaponInfo()
    local weaponInfo = Game.WeaponInfo.New()
    weaponInfo.SkinId = 1
    weaponInfo.No = 1
    weaponInfo.Damage = 20
    weaponInfo.ShootOffset = Vector3.New(0, 0, 0.7)
    weaponInfo.BulletSpeed = self.ecsWorld.BulletSpeed
    weaponInfo.BulletScale = Vector3.New(0.3, 1, 1)
    weaponInfo.BoxSize = Vector3.New(1, 1, 1)
    return weaponInfo
end

return WeaponNo1