---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2019/5/21 22:48
---

local AutoMove = require('Game.Modules.Battle.Behaviors.AutoMove')
local BaseBehavior = require('Game.Modules.Common.Behavior.BaseBehavior')

---@class Game.Modules.Battle.Behaviors.AvatarBehavior : Game.Modules.Common.Behavior.BaseBehavior
---@field avatar Game.Modules.Battle.Items.Avatar
---@field target Game.Modules.Battle.Items.Avatar
---@field autoMove Game.Modules.Battle.Behaviors.AutoMove
---@field currArea Game.Modules.Battle.Behaviors.BornArea
local AvatarBehavior = class("Game.Modules.Battle.Behaviors.AvatarBehavior",BaseBehavior)

local s_id = 1

---@param avatar Game.Modules.Battle.Items.Avatar
function AvatarBehavior:Ctor(avatar)
    s_id = s_id + 1
    AvatarBehavior.super.Ctor(self, avatar.gameObject)
    self.avatar = avatar
    self.autoMove = AutoMove.New(self.avatar)
    self.startTime = 0
end


function AvatarBehavior:SearchTarget()
    local behavior = self:CreateBehavior()

    behavior:AppendState(Handler.New(function()
        if self:isTargetValid() then
            self:NextState() --无需变更攻击目标
        else
            local target = self.currArea:GetNearestTarget(self.avatar)
            if target then
                self.target = target
                self:NextState()
            else
                self.target = nil
                self:Debug("No target")
                self:NextState()
            end
        end
    end , self))

    return behavior
end


--移动到刷怪区域
function AvatarBehavior:MoveToTarget()
    local behavior = self:CreateBehavior()

    behavior:AppendState(Handler.New(self.DoWaitingTargetMoveEnd, self, behavior))
    behavior:AppendState(Handler.New(self.DoMoveToTarget, self))

    return behavior
end

---@param behavior Game.Modules.Common.Behavior.BaseBehavior
function AvatarBehavior:DoWaitingTargetMoveEnd(behavior)
    self:StartCoroutine(function()
        if self:isTargetValid() then
            while self.target.isMoving do
                coroutine.step(1)
            end
            behavior:NextState()
        else
            self:NextState()
        end
    end)
end

function AvatarBehavior:DoMoveToTarget()
    if self:isTargetValid() then
        self:Debug("AvatarBehavior:DoMoveToTarget")
        local tagNode = self.target:GetNearestNode(self.avatar,1)
        if AStarTools.DistanceNode(tagNode, self.avatar.node) == 1 then
            self.avatar:PlayRun()
            self.autoMove:MoveDirect(tagNode.worldPosition, Handler.New(self.OnMoveToTargetEnd,self))
        else
            local tagPos = tagNode.worldPosition
            self.avatar:PlayRun()
            self.autoMove:Move(tagPos, Handler.New(self.OnMoveToTargetEnd,self))
        end
    else
        self:NextState()
    end
end

function AvatarBehavior:OnMoveToTargetEnd()
    self:Debug("AvatarBehavior:OnMoveToTargetEnd")
    self.avatar:PlayIdle()
    self:NextState()
end


--共计单个目标知道目标死亡
function AvatarBehavior:AttackUntilTargetDead()

end

--一轮攻击开始
---@param behavior Game.Modules.Common.Behavior.BaseBehavior
function AvatarBehavior:AttackStart(behavior)
    behavior:AppendState(Handler.New(function()
        if self:isTargetAttackValid() then
            self:Debug("AttackStart")
            behavior:NextState()
        else
            self:NextState()
        end
    end, self))
end

--接技能
---@param behavior Game.Modules.Common.Behavior.BaseBehavior
---@param skillInfo SkillInfo
function AvatarBehavior:AppendSkill(behavior, skillInfo)
    behavior:AppendState(Handler.New(function()
        if self:isTargetAttackValid() then
            Math3D.LookAt_XZ(self.avatar.transform, self.target.transform)
            local length = self.avatar.animCtrl:GetAnimLength(skillInfo.animName)
            for i = 1, #skillInfo.accounts do
                self.avatar.animCtrl:CreateDelay(length * skillInfo.accounts[i].percent, Handler.New(function()
                    self:OnAccountSkill(self.target, skillInfo, skillInfo.accounts[i])
                end, self))
            end
            if self.startTime ~= 0 then
                logError("AppendSkill error.animName:" .. skillInfo.animName)
            end
            self.startTime = Time.time
            self:Debug("AppendSkill.animName:" .. skillInfo.animName)
            --self.avatar.animCtrl:CreateDelay(length,Handler.New(self.OnSkillEnd, self, behavior, skillInfo))
            self.avatar.animCtrl:PlayAnim(skillInfo.animName,Handler.New(self.OnSkillEnd, self, behavior, skillInfo))
        else
            --目标不可攻击
            behavior:NextState()
        end
    end, self))
end

---@param behavior Game.Modules.Common.Behavior.BaseBehavior
---@param skillInfo SkillInfo
function AvatarBehavior:OnSkillEnd(behavior, skillInfo)
    self:Debug("OnSkillEnd.animName:" .. skillInfo.animName .. "  ".. (Time.time - self.startTime))
    behavior:NextState()
    self.startTime = 0
end

---@param target Game.Modules.Battle.Items.Avatar
---@param skillInfo SkillInfo
---@param accountInfo AccountInfo
function AvatarBehavior:OnAccountSkill(target, skillInfo, accountInfo)
    if self:isTargetAccountValid(target) then
        local atkAttr = self.avatar.avatarInfo.attr
        local defAttr = target.avatarInfo.attr
        local skillAtk = math.random(accountInfo.baseAttr.atkMin,accountInfo.baseAttr.atkMax)
        local crit = math.random(accountInfo.baseAttr.critMin,accountInfo.baseAttr.critMax)
        local damage = atkAttr.atk + skillAtk - defAttr.def --技能攻击 + 本身攻击 - 目标防御
        defAttr.hp = Mathf.Max(0, defAttr.hp - damage)
        if defAttr.hp == 0 then
            local event = {}
            event.type = BattleEvent.TargetDead
            event.target = self.target
            BattleEvent.Dispatch(event)
        end
    else

    end
end

--一轮攻击结束
---@param behavior Game.Modules.Common.Behavior.BaseBehavior
function AvatarBehavior:AttackEnd(behavior)
    behavior:AppendState(Handler.New(function()
        self:NextState()
    end, self))
end


--目标的有效性
function AvatarBehavior:isTargetValid()
    if self.target == nil or self.target:IsDead() then
        return false
    else
        return true
    end
end

--目标可被攻击
function AvatarBehavior:isTargetAttackValid()
    return self:isTargetValid()
end

--目标可被伤害结算
function AvatarBehavior:isTargetAccountValid(target)
    if target == nil or target:IsDead() then
        return false
    else
        return true
    end
end

--自身是否可以攻击
function AvatarBehavior:isSelfAttackable()
    if self.avatar.isWakeup then
        return true
    else
        return false
    end
end
function AvatarBehavior:Dispose()
    AvatarBehavior.super.Dispose(self)
    if self.autoMove then
        self.autoMove:Dispose()
    end
end

return AvatarBehavior