---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2019/5/21 22:48
---

local BaseBehavior = require('Game.Modules.Common.Behavior.BaseBehavior')

---@class Game.Modules.Battle.Behaviors.BattleBehavior : Game.Modules.Common.Behavior.BaseBehavior
---@field checkPointData CheckPointData
---@field context WorldContext
local BattleBehavior = class("Game.Modules.Battle.Behaviors.BattleBehavior",BaseBehavior)

---@param checkPointData CheckPointData
---@param context UnityEngine.GameObject
function BattleBehavior:Ctor(checkPointData, context)
    BattleBehavior.super.Ctor(self)
    self.context = context
    self.checkPointData = checkPointData
end

--创建战场
function BattleBehavior:CreateBattle()

end

--重置战场从头开始（阵型变化后调用）
function BattleBehavior:ResetBattle()

end

--新的队列
function BattleBehavior:NewQueue()

end
--统计对象池
---@param sceneData CheckPointData
---@return table<number,PoolInfo>
function BattleBehavior:CalPoolsNum(sceneData)

end

--获取当前区域
---@return Game.Modules.Battle.Layouts.AreaBase
function BattleBehavior:GetCurrArea()

end

--下一区域
function BattleBehavior:NextArea()

end


--获取某阵营所有单位
---@param camp Camp
---@param includeDead boolean 是否包含死亡单位
---@return List | table<number, Game.Modules.World.Items.Avatar>
function BattleBehavior:GetCampAvatarList(camp, includeDead)
    if camp == Camp.Atk then
        local heroList = self.context.battleItemList
        if not includeDead then
            local tempList = List.New()
            for i = 1, #heroList do
                if not heroList[i]:IsDead() and heroList[i].layoutIndex ~= 0 then
                    tempList:Add(heroList[i])
                end
            end
            return tempList
        else
            return List.New(heroList)
        end
    else
        local tempList = List.New()
        if self:GetCurrArea() then
            local monsterList = self:GetCurrArea().currWave.itemList
            if not includeDead then
                for i = 1, monsterList:Size() do
                    if not monsterList[i]:IsDead() then
                        tempList:Add(monsterList[i])
                    end
                end
                return tempList
            else
                return monsterList
            end
        else
            return tempList
        end
    end
end

--回到起点
function BattleBehavior:Clear()
    self:_debug("强制清场")
    if self:GetCurrArea() then
        self:GetCurrArea():Clear()
    end
end

function BattleBehavior:Dispose()
    BattleBehavior.super.Dispose(self)
    for i = 1, #self.bornAreas do
        self.bornAreas[i]:Dispose()
    end
end

return BattleBehavior