---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2019/5/22 22:43
---

local BaseBehavior = require('Game.Modules.Common.Behavior.BaseBehavior')
local AvatarBehavior = require('Game.Modules.Battle.Behaviors.AvatarBehavior')

---@class Game.Modules.Battle.Behaviors.HeroBehavior : Game.Modules.Battle.Behaviors.AvatarBehavior
---@field New fun() : Game.Modules.Battle.Behaviors.HeroBehavior
---@field hero Game.Modules.Battle.Items.Hero
local HeroBehavior = class("Game.Modules.Battle.Behaviors.HeroBehavior",AvatarBehavior)

---@param hero Game.Modules.Battle.Items.Hero
function HeroBehavior:Ctor(hero)
    self.hero = hero
    HeroBehavior.super.Ctor(self, hero)
end

function HeroBehavior:Dispose()
    HeroBehavior.super.Dispose(self)
end

return HeroBehavior