---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2019/1/19 0:21
---

local ListItemRenderer = require("Betel.UI.ListItemRenderer")
---@class Game.Modules.Card.View.CardItem: Betel.UI.ListItemRenderer
local CardItem = class("Game.Modules.Login.View.ServerItem",ListItemRenderer)

local RankFrame =
{
    [1] = "Atlas/PostCard/dikuang_16_1_6.png",
    [2] = "Atlas/PostCard/dikuang_16_1_1.png",
    [3] = "Atlas/PostCard/dikuang_16_1_2.png",
    [4] = "Atlas/PostCard/dikuang_16_1_3.png",
    [5] = "Atlas/PostCard/dikuang_16_1_4.png",
    [6] = "Atlas/PostCard/dikuang_16_1_5.png",
}

---@param gameObject UnityEngine.GameObject
function CardItem:Ctor(gameObject)
    CardItem.super.Ctor(self,gameObject)
end

function CardItem:UpdateItem(data, index)
    local maskImg = self.gameObject:GetImage("Mask")
    maskImg.sprite = Res.LoadSprite(RankFrame[1])
    maskImg.type = UnityEngine.UI.Image.Type.Sliced
end

function CardItem:OnDestroy()

end

return CardItem