---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2020-06-14-20:19:12
---

local DrawCardItem = require("Game.Modules.Card.View.DrawCardItem")
local BaseMediator = require("Game.Core.Ioc.BaseMediator")
---@class Game.Modules.Card.View.DrawCardListMdr : Game.Core.Ioc.BaseMediator
---@field cardModel Game.Modules.Card.Model.CardModel
---@field cardService Game.Modules.Card.Service.CardService
local DrawCardListMdr = class("Game.Modules.Card.View.DrawCardListMdr",BaseMediator)

function DrawCardListMdr:OnInit()
    self:SetCloseBg(self.gameObject:FindChild("Bg"))
    self.cardList = TableList.New(self.gameObject:FindChild("List/ListView"), DrawCardItem)
    self.cardList:SetData(self.cardModel.drawCardList)
    --self.cardList.eventDispatcher:AddEventListener(ListViewEvent.ItemClick,self.onItemClick, self)
end

return DrawCardListMdr
