---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2019/1/19 0:21
---

local ListItemRenderer = require("Betel.UI.ListItemRenderer")
---@class Game.Modules.Card.View.DrawCardItem: Betel.UI.ListItemRenderer
local DrawCardItem = class("Game.Modules.Login.View.ServerItem",ListItemRenderer)

---@param gameObject UnityEngine.GameObject
function DrawCardItem:Ctor(gameObject)
    DrawCardItem.super.Ctor(self,gameObject)
end

---@param drawCardVo Game.Modules.Card.Vo.DrawCardVo
function DrawCardItem:UpdateItem(drawCardVo, index)
    --local frameImg = self.gameObject:GetImage("Frame")
    --frameImg.sprite = Res.LoadSprite(RankFrame[drawCardVo.cardInfo.rarity])

    local iconImg = self.gameObject:GetImage("Icon")
    iconImg.sprite = Res.LoadSprite(drawCardVo.cardInfo.iconUrl)
    --iconImg:SetNativeSize()

    local starBar = self.gameObject:FindChild("StarBar")
    self:SetStar(starBar, drawCardVo.cardInfo.star)
    starBar:SetActive(drawCardVo.fragmentStoneNum == 0)

    local numText = self.gameObject:GetText("Num")
    numText.text = "x" .. drawCardVo.fragmentStoneNum
    numText.gameObject:SetActive(drawCardVo.fragmentStoneNum > 0)
end

---@param starBar UnityEngine.GameObject
function DrawCardItem:SetStar(starBar, starNum)
    for i = 1, starBar.transform.childCount do
        local starImg = starBar.transform:GetChild(i - 1).gameObject:GetImage()
        starImg.sprite = UITools.GetSprite(starImg.gameObject, i <= starNum and 1 or 0)
    end
end

function DrawCardItem:OnDestroy()

end

return DrawCardItem