---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2019/1/10 0:17
---

local Action = {}

Action.LoginAccount = { server = "AccountServer", action = "account@account_login", fields = "username,password" }

Action.LoginRegister = { server = "AccountServer", action = "account@account_register", fields = "username,password" }

Action.LoginLobbyServer = { server = "LobbyServer", action = "player@player_login", fields = "aid,token"}

Action.FetchRandomName = { server = "LobbyServer", action = "role@role_random_name", fields = "playerId"}

Action.CreateRole = { server = "LobbyServer", action = "role@role_create", fields = "playerId,roleName"}

Action.EnterGame = { server = "LobbyServer", action = "role@role_enter_game", fields = "playerId" }

Action.JoinMatch = { server = "LobbyServer", action = "match@join_match", fields = "roleId,game,gameMode" }

--推送房间信息
Action.PushRoomInfo = "push@room_info"

--推送其他玩家进入房间
Action.PushEnterRoom = "push@enter_room"

--推送其他玩家退出房间
Action.PushExitRoom = "push@exit_room"

--手动创建房间
Action.CreateRoom = { server = "RoomServer", action = "room@create_room", fields = "roleId,game,gameMode,robotNum" }

--手动进入房间
Action.EnterRoom = { server = "LobbyServer", action = "match@enter_room", fields = "roleId,roomId,roomPos,isRobot" }

--手动退出房间
Action.ExitRoom = { server = "RoomServer", action = "room@exit_room", fields = "roleId,roomId" }

--玩家状态改变
Action.ChangeState = { server = "RoomServer", action = "room@role_state", fields = "roomId,roleId,roleState,isRobot" }

--推送玩家状态
Action.PushRoomRoleState = "push@room_role_state"

--推送开始加载
Action.PushRoomLoadStart = "push@load_start"

--推送开始加载
Action.PushRoomGameStart = "push@game_start"

--推送发牌
Action.PushHJCardSlot = "push@hj_card_slot"

--推送轮到谁出牌
Action.PushHJWhoseTurn = "push@hj_whose_turn"

return Action