---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2019/1/10 0:17
---

---@class Action
---@field server string
---@field action string
---@field fields string

local Action = {}

---==================
--- 登陆相关
---==================
Action.LoginAccount = { server = "AccountServer", action = "account@accountLogin", fields = "username,password" }

Action.LoginRegister = { server = "AccountServer", action = "account@accountRegister", fields = "username,password" }

Action.LoginGameServer = { server = "GameServer", action = "player@login", fields = "aid,token"}

Action.EnterGame = { server = "GameServer", action = "role@enterGame", fields = "playerId" }

Action.FetchRandomName = { server = "GameServer", action = "role@randomName", fields = "playerId"}

Action.CreateRole = { server = "GameServer", action = "role@roleCreate", fields = "playerId,roleName"}


---==================
--- Card
---==================
--获取当前角色所拥有卡牌信息
Action.CardInfo = { server = "GameServer", action = "Card@cardInfo", fields = "roleId" }

--卡池信息
Action.CardInfo = { server = "GameServer", action = "Card@cardPoolInfo", fields = "" }

--抽卡
Action.CardInfo = { server = "GameServer", action = "Card@cardInfo", fields = "poolId,type" }

--推送房间信息
Action.PushRoomInfo = "push@room_info"

--推送其他玩家进入房间
Action.PushEnterRoom = "push@enter_room"

--推送其他玩家退出房间
Action.PushExitRoom = "push@exit_room"

--手动创建房间
Action.CreateRoom = { server = "RoomServer", action = "room@create_room", fields = "roleId,game,gameMode,robotNum" }

--手动进入房间
Action.EnterRoom = { server = "LobbyServer", action = "match@enter_room", fields = "roleId,roomId,roomPos,isRobot" }

--手动退出房间
Action.ExitRoom = { server = "RoomServer", action = "room@exit_room", fields = "roleId,roomId" }

--玩家状态改变
Action.ChangeState = { server = "RoomServer", action = "room@role_state", fields = "roomId,roleId,roleState,isRobot" }

--推送玩家状态
Action.PushRoomRoleState = "push@room_role_state"

--推送开始加载
Action.PushRoomLoadStart = "push@load_start"

--推送开始加载
Action.PushRoomGameStart = "push@game_start"

--推送发牌
Action.PushHJCardSlot = "push@hj_card_slot"

--推送轮到谁出牌
Action.PushHJWhoseTurn = "push@hj_whose_turn"

return Action