---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhengnan.
--- DateTime: 2018/6/19 18:18
---

---@class Game.Core.Ioc.BaseModel : Betel.LuaObject
local LuaObject = require('Betel.LuaObject')
local BaseModel = class("BaseModel",LuaObject)

function BaseModel:Ctor()

end

return BaseModel