---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhengnan.
--- DateTime: 2019/5/2 15:55
--- 所有场景单位的基类
---

local LuaObject = require("Betel.LuaObject")

---@class Game.Modules.World.Items.SceneUnit : Betel.LuaObject
---@field sid number 唯一id
---@field context WorldContext
---@field sceneItemVo Game.Modules.World.Vo.SceneUnitVo
---@field gameObject UnityEngine.GameObject
---@field transform UnityEngine.Transform
local SceneItem = class("Game.Modules.World.Items.SceneUnit", LuaObject)

local S_ID = 0

---@param sceneItemData Game.Modules.World.Vo.SceneUnitVo
function SceneItem:Ctor(sceneItemData)
    SceneItem.super.Ctor(self)
    self.sceneItemVo = sceneItemData
    if self.sceneItemVo.sid == nil then
        S_ID = S_ID + 1
        self.sceneItemVo.sid = S_ID
    end
    self.sid = self.sceneItemVo.sid

    self.gameObject = GameObject.New("SceneItem_" .. self.sid)
    self.transform = self.gameObject.transform
    self:OnInitialize()
    --self:EnableDestroyListener()
end

---@param context WorldContext
function SceneItem:SetContext(context)
    self.context = context
end

function SceneItem:SetParent()

end

function SceneItem:OnInitialize()

end

--回收
function SceneItem:Recovery()

end

--释放资源
function SceneItem:Dispose()

end

function SceneItem:Destroy()

end

function SceneItem:OnDestroy()
    SceneItem.super.OnDestroy(self)
end


return SceneItem