---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2019/5/22 22:43
---

local MainHeroBehavior = require("Game.Modules.Battle.Behaviors.MainHeroBehavior")
local Hero = require('Game.Modules.Battle.Items.Hero')

---@class Game.Modules.Battle.Items.MainHero : Game.Modules.Battle.Items.Hero
---@param behavior Game.Modules.Battle.Behaviors.MainHeroBehavior
local MainHero = class("Game.Modules.Battle.Items.MainHero",Hero)

---@param heroInfo HeroInfo
function MainHero:Ctor(heroInfo)
    MainHero.super.Ctor(self, heroInfo)
end

function MainHero:OnLoadedRenderObj()
    MainHero.super.OnLoadedRenderObj(self)
    --self.behavior = MainHeroBehavior.New(self.gameObject)
    --self:SetRenderObjVisible(false)
end


---@param enable boolean
function MainHero:SetBehaviorEnable(enable)
    if self.behavior then
        self.behavior:Dispose()
    end
    if enable then
        self.behavior = MainHeroBehavior.New(self)
        self.behavior:Run()
    end
end

function MainHero:Dispose()
    MainHero.super.Dispose(self)
end

return MainHero