---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2019/5/31 0:17
---

local LuaMonoBehaviour = require('Betel.LuaMonoBehaviour')

---@class Game.Modules.Battle.Items.SceneItemHUD : Betel.LuaMonoBehaviour
---@field New fun(gameObject:UnityEngine.GameObject) : Game.Modules.Battle.Items.SceneItemHUD
---@field avatar Game.Modules.Battle.Items.Avatar
---@field hp UnityEngine.TextMesh
---@field name UnityEngine.TextMesh
local SceneItemHUD = class("Game.Modules.Battle.Items.SceneItemHUD", LuaMonoBehaviour)

local Offset_Y = 2.1

---@param avatar Game.Modules.Battle.Items.Avatar
function SceneItemHUD:Ctor(avatar)
    self.gameObject = Instantiate("Prefabs/Scene/SceneHUD.prefab",self.transform)
    SceneItemHUD.super.Ctor(self, self.gameObject)
    self.avatar = avatar
    self:Init()
    AddEventListener(Event.Update, self.Update, self)
end

function SceneItemHUD:Init()
    self.hp = GetText3D(self.gameObject:FindChild("hp"))
    self.name = GetText3D(self.gameObject:FindChild("name"))
    self.hud = Hud.New(self.avatar.avatarInfo.name,1)
    self.hud.transform:SetParent(self.transform)
    self.hud.transform.gameObject:ResetTransform()
    self:Update()
end

function SceneItemHUD:Update()
    local attr = self.avatar.avatarInfo.attr
    self.hud:UpdateHud(Mathf.Max(0, attr.hp / attr.hpMax))
    --self.hp.text = attr.hp .. "/" .. attr.hpMax
    --self.name.text =  self.avatar.avatarInfo.name
    self.transform.position = self.avatar.transform.position + Vector3.New(0,Offset_Y,0)
end

function SceneItemHUD:Dispose()
    SceneItemHUD.super.Dispose(self)
    destroy(self.gameObject)
    RemoveEventListener(Event.Update, self.Update, self)
end

return SceneItemHUD