---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2020/4/9 21:00
--- 主场景:可以有子场景
---

local BaseScene = require('Game.Modules.World.Scenes.Core.BaseScene')

---@class Game.Modules.World.Scenes.Core.MainScene : Game.Modules.World.Scenes.Core.BaseScene
---@field New fun(sceneInfo:SceneInfo, unityScene:UnityEngine.SceneManagement.Scene)
---@field unityScene UnityEngine.SceneManagement.Scene
---@field sceneInfo SceneInfo
---@field currSubSceneInfo SubSceneInfo
---@field currSubScene Game.Modules.World.Scenes.Core.SubScene
local MainScene = class("Game.Modules.World.Scenes.Core.MainScene",BaseScene)

---@param sceneInfo SceneInfo
---@param unityScene UnityEngine.SceneManagement.Scene
function MainScene:Ctor(sceneInfo, unityScene)
    MainScene.super.Ctor(self, unityScene)
    self.sceneInfo = sceneInfo
    self:Init()
end

function MainScene:Init()
    vmgr:SetScene(self)
end

function MainScene:EnterSubScene(subLevel, callback)
    if self.currSubScene then
        if self.currSubScene.subSceneInfo.level == subLevel then
            --同样的场景无需更换
            if callback ~= nil then
                callback(self.currSubScene)
            end
        else
            self.currSubScene:OnExitScene()
            self.currSubScene:Unload(function()
                self:LoadSubLevel(subLevel, callback)
            end)
        end
    else
        self:LoadSubLevel(subLevel, callback)
    end
end

function MainScene:LoadSubLevel(subLevel, callback)
    if self.sceneInfo.subLevels == nil or self.sceneInfo.subLevels[subLevel] == nil then
        logError("There is no sub levels in this scene: "..subLevel)
    else
        local subSceneInfo = self.sceneInfo.subLevels[subLevel]
        sceneMgr:LoadSubSceneAsync(subSceneInfo.level, function (unityScene)
            local subSceneClass = require(subSceneInfo.sceneClass)
            local subScene = subSceneClass.New(subSceneInfo, unityScene) ---@type Game.Modules.World.Scenes.Core.SubScene
            log("加载子场景完成:"..subSceneInfo.level)
            self.currSubSceneInfo = subSceneInfo
            self.currSubScene = subScene
            subScene:Init()
            subScene:OnEnterScene()
            if callback ~= nil then
                callback(subScene)
            end
        end)
    end
end

return MainScene