---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2020-07-21-23:18:25
---

local CheckPointReportItem = require("Game.Modules.CheckPoint.View.CheckPointReportItem")
local BaseMediator = require("Game.Core.Ioc.BaseMediator")
---@class Game.Modules.CheckPoint.View.CheckPointReportMdr : Game.Core.Ioc.BaseMediator
---@field checkPointModel Game.Modules.CheckPoint.Model.CheckPointModel
---@field battleModel Game.Modules.Battle.Model.BattleModel
---@field checkPointService Game.Modules.CheckPoint.Service.CheckPointService
---@field battleService Game.Modules.Battle.Service.BattleService
local CheckPointReportMdr = class("Game.Modules.CheckPoint.View.CheckPointReportMdr",BaseMediator)


function CheckPointReportMdr:Ctor()
    CheckPointReportMdr.super.Ctor(self)
    self.layer = UILayer.LAYER_FLOAT
end

function CheckPointReportMdr:OnInit()
    self.battleService:GetBattleReportList(
            self.checkPointModel.currSection.checkPointData.chapter,
            self.checkPointModel.currSection.checkPointData.id, Handler.New(self.OnBattleReportList, self))
end

function CheckPointReportMdr:OnBattleReportList()
    self.reportItemList = TableList.New(self.gameObject:FindChild("List/ListView"), CheckPointReportItem)
    self.reportItemList:SetData(List.New(self.battleModel.checkpointReports))
    self.reportItemList.eventDispatcher:AddEventListener("CheckPointReportReplay", self.CheckPointReportReplay, self)
end

function CheckPointReportMdr:CheckPointReportReplay(event)
    self.battleService:GetBattleReport(event.reportVo.id, function()
        self.battleModel.isReplayReport = true
        self:Unload()
    end)
end

return CheckPointReportMdr
