---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2020/4/10 23:37
---

local BattleItem = require("Game.Modules.World.Items.BattleItem")

---@class WorldContext
---@field New fun()
---@field mode string
---@field id number
---@field currSubScene Game.Modules.World.Scenes.Core.SubScene  当前子场景
---@field battleBehavior Game.Modules.Battle.Behaviors.BattleBehavior    战场行为
---@field battleItemList table<number, Game.Modules.World.Items.BattleItem>
---@field avatarRoot UnityEngine.GameObject
---@field pool Game.Modules.Common.Pools.AssetPoolProxy 对象池
---@field attachCamera Game.Modules.Common.Components.AttachCamera
---@field battleLayout Game.Modules.Battle.View.BattleLayout
local WorldContext = class("WorldContext")

local Sid = 1

function WorldContext:Ctor(mode)
    self.id = Sid
    Sid = Sid + 1
    self.mode = mode
    self.battleItemList = {}
    self.dropList = List.New()
end

--创建可以战斗的单位
---@param camp Camp 所属阵营
---@param cards table<number, Game.Modules.Card.Vo.CardVo> 卡牌
---@param state CardState
function WorldContext:CreateBattleItems(cards, camp, state)
    for i = 1, #cards do
        local card = cards[i]
        if state == nil or card.state == state then
            local battleItem = self:CreateBattleItem(card, camp)
            table.insert(self.battleItemList, battleItem)
            battleItem.layoutIndex = card.layoutIndex
        end
    end
end

---@param card Game.Modules.Card.Vo.CardVo 卡牌
function WorldContext:CreateBattleItem(card, camp)
    local battleItemVo = World.CreateBattleItemVo(card.cardInfo.avatarName)
    battleItemVo.camp = camp
    battleItemVo.isLeader = card.layoutIndex == 1
    battleItemVo.index = card.layoutIndex
    local battleItem = BattleItem.New(battleItemVo, self)
    battleItem.ownerCardVo = card
    return battleItem
end

---@param hero Game.Modules.World.Items.BattleItem
function WorldContext:AddBattleItem(hero)
    table.insert(self.battleItemList, hero)
    hero.layoutIndex = hero.ownerCardVo.layoutIndex
end

---@param cardInfo Game.Modules.Card.Vo.CardVo
---@return Game.Modules.World.Items.BattleItem
function WorldContext:GetBattleItemByCard(cardInfo)
    for i = 1, #self.battleItemList do
        if self.battleItemList[i].ownerCardVo == cardInfo then
            return self.battleItemList[i]
        end
    end
    --logError("There is no hero with card:" .. cardInfo.cardInfo.avatarName)
    return nil
end

---@param hero Game.Modules.World.Items.Hero
function WorldContext:RemoveBattleItem(hero)
    for i = 1, #self.battleItemList do
        if self.battleItemList[i] == hero then
            self.battleItemList[i]:Dispose()
            table.remove(self.battleItemList, i)
            break
        end
    end
end

function WorldContext:Dispose()
    for i = 1, #self.battleItemList do
        self.battleItemList[i]:Dispose()
    end
    if self.battleBehavior then
        self.battleBehavior:Dispose()
    end
    if self.attachCamera then
        self.attachCamera:Dispose()
    end
    if self.pool then
        self.pool:Dispose()
    end

    self.battleItemList = nil
    Destroy(self.avatarRoot)
    self.avatarRoot = nil
end

return WorldContext