---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2020-04-12-01:33:50
---

local BaseModel = require("Game.Core.Ioc.BaseModel")
---@class Game.Modules.Card.Model.CardModel : Game.Core.Ioc.BaseModel
---@field cardService Game.Modules.Card.Service.CardService
---@field cardList List | table<number, Game.Modules.Card.Vo.CardVo>
---@field cardPoolList List | table<number, Game.Modules.Card.Vo.CardPoolVo>
local CardModel = class("CardModel",BaseModel)

function CardModel:Ctor()

end


return CardModel
