---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhengnan.
--- DateTime: 2020/3/10 15:54
---

---@class ViewEvents
---@field type string @ 指针事件附带的数据
---@field viewInfo Game.Manager.ViewInfo
local ViewEvents = {}

--- 视图加载完成
ViewEvents.Loaded = "ViewEvents Loaded"

--- 视图加载卸载完成
ViewEvents.Unloaded = "ViewEvents Unloaded"
--
---@param event ViewEvents
function ViewEvents.DispatchEvent(event)
    edp:DispatchEvent(event)
end

return ViewEvents