---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2020/6/29 22:40
--- 飘字
---

local AssetPool = require("Game.Modules.Common.Pools.AssetPool")
local SceneUnitHUD = require('Game.Modules.Battle.Components.SceneUnitHUD')

---@class Game.Modules.Battle.Components.FloatNumber : Game.Modules.Battle.Components.SceneUnitHUD
---@field pool Game.Modules.Common.Pools.AssetPool\
local FloatNumber = class("Game.Modules.Battle.Components.FloatNumber", SceneUnitHUD)

local Offset = Vector3.New(0,80,0)

---@param battleUnit Game.Modules.World.Items.BattleUnit
function FloatNumber:Ctor(battleUnit)
    FloatNumber.super.Ctor(self, battleUnit)
end

function FloatNumber:Init()
    FloatNumber.super.Init(self)
end

function FloatNumber:Update()

end

function FloatNumber:Play(dam)
    local obj = self.battleUnit.context.pool:CreateObjectByPool(Prefabs.FloatNumber)
    Layers.SetLayer(obj, Layers.UI())
    obj.name = "FloatNumber"
    local pos = self:GetTargetUIPos(Offset)
    obj.transform:SetParent(self.uiLayer)
    obj.transform.localPosition = pos
    obj.transform.localScale = Vector3.one
    obj.transform.localEulerAngles = Vector3.zero
    local damText = obj:GetText("Dam")
    damText.transform:DOPause()
    damText.text = dam
    damText.transform.localPosition = Vector3.zero
    damText.transform:DOLocalJump(pos + Vector3.right * (1 + math.random() * 5),60,1,(0.6 + math.random()*0.1),true):OnComplete(function ()
        self.battleUnit.context.pool:StoreObject(Prefabs.FloatNumber, obj)
    end)
end

function FloatNumber:Dispose()
    FloatNumber.super.Dispose(self)
end

return FloatNumber