---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2020/6/15 22:25
---

---@class Game.Modules.Role.Events.RoleEvents
---@field roleVo Game.Modules.World.Items.Hero
---@field callback Handler
local RoleEvents = {}

--获取资源
RoleEvents.GetResource    = "Role_GetResource"

--资源更新
RoleEvents.UpdateResource    = "Role_UpdateResource"

function RoleEvents.Dispatch(event)
    edp:DispatchEvent(event,false, false)
end

---@param roleVo Game.Modules.World.Items.Hero
function RoleEvents.DispatchEvent(type, roleVo)
    local event = {}
    event.type = type
    event.roleVo = roleVo
    edp:DispatchEvent(event,false, false)
end

return RoleEvents