---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhengnan.
--- DateTime: 2019/9/21 14:13
---

local WeaponNo1 = require("Game.Modules.Battle.Weapon.WeaponNo1")

---@class C_ChangeWeapon
---@field ecsWorld Game.WeaponInfo
---@field weapon table<number, Game.Modules.Battle.Weapon.WeaponBase>
local C_ChangeWeapon = {}

---@param ecsWorld Game.ECSWorld
function C_ChangeWeapon.init(ecsWorld)
    print("C_ChangeWeapon init")

    C_ChangeWeapon.ecsWorld = ecsWorld

    self.weapon = {}
    self.weapon[1] = WeaponNo1.New(ecsWorld)
end


function C_ChangeWeapon.SetWeaponNo()

end

function C_ChangeWeapon.SetWeaponLevel()

end

return C_ChangeWeapon