---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2020/7/13 21:26
---

---@class Game.Modules.Battle.Report.Nodes.ReportNode
---@field New fun():Game.Modules.Battle.Report.Nodes.ReportNode
---@field skillId number
---@field skillLevel number
---@field accountNodes table<number, Game.Modules.Battle.Report.Nodes.AccountNode>
local ReportNode = class("Game.Modules.Battle.Report.Nodes.ReportNode");

function ReportNode:Ctor(data)
    self.id = data.id
    self.skillId = data.skillId
    self.skillLevel = data.skillLevel
end

return ReportNode