---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2019/5/23 22:51
---

---@class Game.Modules.Battle.Events.BattleEvents
---@field target Game.Modules.World.Items.Avatar
---@field hero Game.Modules.World.Items.Hero
---@field monster Module.World.Items.Monster
---@field callback Handler
local BattleEvents = {}

--开始战斗
BattleEvents.BattleStart    = "GridBattle_BattleStart"

--暂停战斗
BattleEvents.BattlePause    = "GridBattle_BattlePause"

--恢复暂停的战斗
BattleEvents.BattleResume    = "GridBattle_BattleResume"

--单次攻击开始
BattleEvents.EnterAttack = "GridBattle_EnterAttack"

--单次攻击结束
BattleEvents.ExitAttack = "GridBattle_ExitAttack"

--所有怪物死亡
BattleEvents.AllMonsterDead    = "GridBattle_AllMonsterDead"

--所有怪物死亡结束
BattleEvents.AllMonsterDeadOver    = "GridBattle_AllMonsterDeadOver"

function BattleEvents.Dispatch(event)
    DispatchEvent(BattleEvents,event,false, false)
end

---@param item Game.Modules.Battle.Items.SceneItem
function BattleEvents.DispatchItemEvent(type, item)
    local event = {}
    event.type = type
    event.item = item
    DispatchEvent(BattleEvents,event,false, false)
end

return BattleEvents