---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2019/5/23 22:51
---

---@class BattleEvent
---@field type string
---@field target Game.Modules.Battle.Items.Avatar
local BattleEvent = {}

--战场已经创建完毕
BattleEvent.BattleCreated = "BattleCreated"

--目标死亡
BattleEvent.TargetDead = "Battle TargetDead"

--当前区域所有怪物都已经死亡
BattleEvent.AreaAllDead = "Battle AreaAllDead"

--当前区域所有怪物都已经死亡,死亡动作播放完毕
BattleEvent.AreaAllDeadOVer = "Battle AreaAllDeadOVer"


BattleEvent.dispatcher = EventDispatcher.New()

function BattleEvent.Dispatch(event)
    if isString(event) then
        BattleEvent.dispatcher:Dispatcher(event)
    elseif event.type then
        BattleEvent.dispatcher:Dispatcher(event.type, event)
    end
end

return BattleEvent