---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2020/7/4 0:12
--- 回放系统的生成器
---

---@class Game.Modules.Battle.Report.Generator
local Generator = class("Game.Modules.Battle.Report.Generator");

function Generator.Ctor()

end

return Generator