---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2020/7/5 1:37
---

require("Game.Modules.Battle.Report.ReportConsts")

ReportUtils = require("Game.Modules.Battle.Report.ReportUtils")
