---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2020/7/5 0:53
--- 战斗单位
---

---@class Game.Modules.Battle.Report.ReportBattleUnit
---@field battleUnitVo Game.Modules.Battle.Vo.BattleUnitVo
---@field sid number 唯一id
---@field context Game.Modules.Battle.Report.ReportContext
---@field ownerCardVo Game.Modules.Card.Vo.CardVo
---@field currSelectedSkill Game.Modules.Battle.Vo.SkillVo 当前被选中的技能
---@field skills table<number, Game.Modules.Battle.Vo.SkillVo>
---@field skillMap table<string, Game.Modules.Battle.Vo.SkillVo>
---@field layoutIndex number
local ReportBattleUnit = class("Game.Modules.Battle.Report.ReportBattleUnit");

local S_ID = 0

---@param battleUnitVo Game.Modules.Battle.Vo.BattleUnitVo
---@param context Game.Modules.Battle.Report.ReportContext
function ReportBattleUnit:Ctor(battleUnitVo, context)
    S_ID = S_ID + 1
    self.sid = S_ID
    self.context = context
    self.battleUnitVo = battleUnitVo

    self.skills = battleUnitVo.skills
    self.skillMap = {}
    for i = 1, #self.skills do
        self.skillMap[self.skills[i].skillInfo.type] = self.skills[i]
    end
    self.canUseList = List.New()
    self.currTargetAttackNum = 0

    self.debugName = self.battleUnitVo.battleUnitInfo.name .. "_" .. self.battleUnitVo.camp .. "-" .. self.battleUnitVo.layoutIndex

    self.skillLoopIndex = 1
end

---@param s1 Game.Modules.Battle.Vo.SkillVo
---@param s2 Game.Modules.Battle.Vo.SkillVo
local function compFunc(s1, s2)
    if s1 ~= nil and s2 ~= nil then
        return s1.skillInfo.priority > s2.skillInfo.priority
    else
        return false
    end
end

function ReportBattleUnit:IsDead()
    return self.battleUnitVo.curHp == 0
end


function ReportBattleUnit:AutoSelectSkill()
    if self.skillMap[SkillType.UB] ~= nil and
            self.battleUnitVo.curTp > 0 and
            self.battleUnitVo.curTp >= self.battleUnitVo.maxTp and
            self.context:UseUB(self) then--是否满足使用UB技能
        self.currSelectedSkill = self.skillMap[SkillType.UB]
        self.battleUnitVo.curTp = 0
    else--正规输出循环
        self.currSelectedSkill = self.skillMap[SkillLoop[self.skillLoopIndex]]
        while self.currSelectedSkill == nil do
            if self.skillLoopIndex + 1 > #SkillLoop then
                self.skillLoopIndex = 1
            else
                self.skillLoopIndex = self.skillLoopIndex + 1
            end
            self.currSelectedSkill = self.skillMap[self.skillLoopIndex]
        end
    end
end

function ReportBattleUnit:AutoSelectSkill_old()
    self.canUseList:Clear()
    for i = 1, #self.skills do
        local skill = self.skills[i] ---@type Game.Modules.Battle.Vo.SkillVo
        if skill.isNecessary then --必然触发的技能
            self.canUseList:Clear()
            self.canUseList:Add(skill)
            break;
        else
            if skill.skillInfo.skillType == SkillType.Passive then
                -- do nothing被动技能
            elseif skill.skillInfo.cd == 0 or skill.startTime == 0 or Time.time - skill.startTime > skill.skillInfo.cd then
                if skill.skillInfo.triggerCondition == SkillTriggerCondition.CD then -- CD
                    self.canUseList:Add(skill)
                elseif skill.skillInfo.triggerCondition == SkillTriggerCondition.FullTp then -- 满怒气
                    if self.battleUnitVo.curTp >= self.battleUnitVo.maxTp then
                        self.canUseList:Add(skill)
                    end
                elseif skill.skillInfo.triggerCondition == SkillTriggerCondition.Prob then -- 触发概率
                    local prob = math.random()
                    if prob <= tonumber(skill.skillInfo.triggerConditionParam) then
                        self.canUseList:Add(skill)
                    end
                end
            end
        end
    end
    if self.canUseList:Size() > 0 then
        self.canUseList:Sort(compFunc)
        self.canUseList[1].isNecessary = false
        self.currSelectedSkill = self.canUseList[1]
        --self.battleUnit:_debug(self.currSelectedSkill.id)
        --这里暂时默认这个技能肯定被触发了,做一些初始操作
        self.currTargetAttackNum = self.currTargetAttackNum + 1
    else
        --self.avatar:_debugError("there is no skill can use!!")
        self.currSelectedSkill = nil
    end
    return self.currSelectedSkill
end

--调试
function ReportBattleUnit:_debug(msg)
    if self.gameObject then
        print(string.format("\n<color=#3A9BF8FF>[%s]</color><color=#5394ecff>%s</color>",self.debugName,msg))
    else
        print(string.format("\n<color=#3A9BF8FF>[%s]</color><color=#5394ecff>%s</color>",self.__classname,msg))
    end
end

return ReportBattleUnit