---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhengnan.
--- DateTime: 2019/5/6 17:35
---


--Avatar基础属性
---@class AvatarInfo : SceneItemInfo
---@field name string
---@field type number
---@field hudOffset UnityEngine.Vector3

local AvatarConfig = {}

---@return AvatarInfo
function AvatarConfig.Get(avatarName)
    if AvatarConfig.data == nil then
        AvatarConfig.data = require("Game.Data.Excel.AvatarData")
    end
    --if AvatarConfig.skillData == nil then
    --    AvatarConfig.skillData = require("Game.Data.Excel.Skill")
    --end
    --if AvatarConfig.dropData == nil then
    --    AvatarConfig.dropData = require("Game.Data.Excel.DropItem")
    --end
    local info = AvatarConfig.data.Get(avatarName) ---@type AvatarInfo
    if info == nil then
        logError(string.format("There is not avatar info named %s!", avatarName))
    end

    if isString(info.hudOffset) then
        local hudOffset = info.hudOffset
        info.hudOffset = Tool.ToVector3(hudOffset)
    end

    return info
end

return AvatarConfig