---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhengnan.
--- DateTime: 2019/5/6 17:35
---


---@class Game.Modules.Common.Sound.SoundConfig
---@field id number             声音ID
---@field intrc string          声音描述
---@field file string           声音文件
---@field type string           类型:BGM|3D|UI
---@field loopType string       循环类型
---@field beginTime number      起始播放时间
---@field fadeIn number         淡入时间
---@field fadeOut number        淡出时间
---@field blend number          2D 到 3D 效果强度
---@field minDistance number        3d时最小影响距离
---@field maxDistance number        3d时最大影响距离
---@field volumeScale number    音量缩放

local SoundConfig = {}

SoundConfig.data = nil

---@return Game.Modules.Common.Sound.SoundConfig
function SoundConfig.Get(soundName)
    --if SoundConfig.data == nil  then
    --    SoundConfig.data = require("Game.Data.Excel.Sound")
    --end
    --local info = SoundConfig.data.Get(soundName)
    --if info == nil then
    --    logError(string.format("There is not sound info named %s!", soundName))
    --end
    --return info
end

return SoundConfig