---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2019/1/15 0:09
---

local UIView = require('Game.Modules.Common.View.UIView')
---@class Game.Modules.Common.View.Alert : Game.Modules.Common.View.UIView
---@field gameObject UnityEngine.GameObject
---@field one_btnOk UnityEngine.UI.Button
---@field two_btnCancel UnityEngine.UI.Button
---@field two_btnOk UnityEngine.UI.Button
local Alert = class("Alert",UIView)

function Alert.Show(msg,okCallback,param,cancelCallback)
    local alert = Alert.New()
    alert:DisplayShow("Alert",msg,okCallback,param,cancelCallback)
end

function Alert.ShowTitle(title,msg,okCallback,param,cancelCallback)
    local alert = Alert.New()
    alert:DisplayShow(title,msg,okCallback,param,cancelCallback)
end

function Alert.Show2(msg,okCallback,param,cancelCallback)
    local alert = Alert.New()
    alert:DisplayShow("Alert",msg,okCallback,param,cancelCallback)
end

function Alert.ShowTitle2(title,msg,okCallback,param,cancelCallback)
    local alert = Alert.New()
    alert:DisplayShow(title,msg,okCallback,param,cancelCallback)
end

function Alert:Ctor()
    local layer = vmgr:GetUILayer(UILayer.alert)
    Alert.super.Ctor(self, "Prefabs/UI/Common/Alert.prefab",layer)
    self.canvas = self.gameObject:GetCanvasGroup("")
    self.one_btnOk = self.gameObject:GetButton("BtnOneOk");
    self.two_btnCancel = self.gameObject:GetButton("Two/BtnCancel");
    self.two_btnOk = self.gameObject:GetButton("Two/BtnTwoOk");
end

function Alert:DisplayShow(title,msg,okCallback,param,cancelCallback)
    self.okCallback = okCallback
    self.param = param
    self.cancelCallback = cancelCallback
    self.gameObject:GetText("TitleBar/Text").text = title
    self.gameObject:GetText("Text").text = msg
    if cancelCallback ~= nil then
        self.one_btnOk.gameObject:SetActive(false)
        self.two_btnOk.gameObject:SetActive(true)
        self.two_btnCancel.gameObject:SetActive(true)
    else
        self.one_btnOk.gameObject:SetActive(true)
        self.two_btnOk.gameObject:SetActive(false)
        self.two_btnCancel.gameObject:SetActive(false)
    end
end

function Alert:On_Click_BtnClose()
    --log("On_Click_BtnClose")
    self:Destroy()
end

function Alert:On_Click_BtnOneOk()
    --log("On_Click_BtnOneOk")
    if self.okCallback then
        self.okCallback(self.param)
    end
end

function Alert:On_Click_BtnTwoOk()
    --log("On_Click_BtnTwoOk")
    if self.okCallback then
        self.okCallback(self.param)
    end
end

function Alert:On_Click_BtnCancel()
    --log("On_Click_BtnCancel")
    if self.cancelCallback then
        self.cancelCallback(self.param)
    end
end

return Alert