---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2020/6/27 18:52
---

local WorldEvents = require("Game.Modules.World.Events.WorldEvents")
local LuaMonoBehaviour = require("Betel.LuaMonoBehaviour")
---@class Game.Modules.Common.View.Transition
---@field New():Game.Modules.Common.View.Transition
local Transition = class("Game.Modules.Common.View.Transition", LuaMonoBehaviour)

---@param duration number
---@param callback fun()
function Transition:DoTransition(callback, duration)
    self.duration = duration or 1
    local OnTransitionStart
    OnTransitionStart = function()
        invoke(callback)
        RemoveEventListener(WorldEvents, WorldEvents.TransitionStart, OnTransitionStart, self)
        WorldEvents.Dispatch(WorldEvents.TransitionOver)
    end
    AddEventListener(WorldEvents, WorldEvents.TransitionStart, OnTransitionStart , self)
    vmgr:LoadView(ViewConfig.Transition)
end

function Transition:FadeIn(callback, duration)
    self:DoTransition(callback, duration)
end

--进关卡战斗
---@param checkPointName string 关卡名字
function Transition:EnterCheckPoint(checkPointName)
    self:DoTransition(function()
        World.worldScene:EnterCheckPoint(checkPointName)
    end)
end

--清楚导航
function Transition:CleatNavigation(callback)
    self:DoTransition(function()
        navigation:Clear(callback)
    end)
end

return Transition