---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhengnan.
--- DateTime: 2020/1/8 12:03
--- 池对象工厂
---

---@class Game.Modules.Common.Pools.PoolObjectProxy
---@field New fun(class:table):Game.Modules.Common.Pools.PoolObjectProxy
---@field list Iterator 列表
---@field pool List 对象池
local PoolObjectProxy = class("Game.Modules.Common.Pools.PoolObjectProxy")

---@param class table
function PoolObjectProxy:Ctor(class)
    self.voClass = class
    self.list = Iterator.New()
    self.pool = List.New()
end

---@return Game.Modules.Common.Pools.PoolObject
function PoolObjectProxy:Get()
    local vo = self:Pop()
    vo.delete = false
    self.list:Add(vo)
    return vo
end

---@param vo Game.Modules.Common.Pools.PoolObject
function PoolObjectProxy:Store(vo)
    if vo == nil then
        return
    end
    vo.delete = true
    self.list:Remove(vo)
    if not self.pool:Contain(vo) then
        self.pool:UnShift(vo)
    end
end

---@return Game.Modules.Common.Pools.PoolObject
function PoolObjectProxy:Pop()
    if self.pool:Size() > 0 then
        return self.pool:Shift()
    else
        return self.voClass.New()
    end
end

---@param vo Game.Modules.Common.Pools.PoolObject
---@return boolean
function PoolObjectProxy:Contains(vo)
    return self.list.list:Contain(vo)
end

---@return boolean
function PoolObjectProxy:IsEmpty()
    return self.pool:Size() == 0
end

return PoolObjectProxy