---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2020-06-02-23:44:37
---

local BaseVo = require("Game.Core.BaseVo")
---@class Game.Modules.Card.Vo.CardPoolVo : Game.Core.BaseVo
---@field New fun():Game.Modules.Card.Vo.CardPoolVo
---@field name string
---@field maxTimes number
---@field limitDrawPrice number
---@field singleDrawPrice number
---@field seriesDrawPrice number
local CardPoolVo = class("Game.Modules.Card.Vo.CardPoolVo",BaseVo)

function CardPoolVo:Ctor(cardPool)
    self.name = cardPool.id
    self.maxTimes = cardPool.maxTimes
    self.limitDrawPrice = cardPool.limitDrawPrice
    self.singleDrawPrice = cardPool.singleDrawPrice
    self.seriesDrawPrice = cardPool.seriesDrawPrice
end

return CardPoolVo
