---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2019/5/24 23:22
---


---@class World
---@field mdr Game.Modules.World.View.WorldMdr
---@field worldScene Game.Modules.World.Scenes.WorldScene
local World = {}


function World.EnterScene(sceneInfo, callback)
    World.mdr:EnterScene(sceneInfo, callback)
end

function World.EnterSubScene(subLevel, callback)
    World.worldScene:EnterSubScene(subLevel, callback)
end

return World