---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2019/5/24 23:22
---


---@class World
---@field mdr Game.Modules.World.View.WorldMdr
---@field worldScene Game.Modules.World.Scenes.WorldScene
local World = {}


function World.EnterScene(sceneInfo, callback)
    World.mdr:EnterScene(sceneInfo, callback)
end

function World.EnterSubScene(subLevel, callback)
    World.worldScene:EnterSubScene(subLevel, callback)
end

---@param battleUnitName string
---@return Game.Modules.Battle.Vo.BattleUnitVo
function World.CreateBattleUnitVo(battleUnitName)
    local vo = BattleItemVoPool:Get()---@type Game.Modules.Battle.Vo.BattleUnitVo
    vo:Init(battleUnitName)
    return vo
end

---@param skillVo Game.Modules.Battle.Vo.SkillVo
---@param attacker Game.Modules.World.Items.Avatar
---@param account AccountInfo
---@return Module.World.Contexts.AccountContext
function World.CreateAccountContext(skillVo, attacker, account)
    local accountContext = AccountContextPool:Get()---@type Module.World.Contexts.AccountContext
    accountContext:Init(skillVo, attacker, account)
    return accountContext
end

return World