---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2019/5/24 23:22
---


---@class World
---@field mdr Game.Modules.World.View.WorldMdr
---@field battleSubScene Game.Modules.World.Scenes.SubScene
---@field battleBehavior Game.Modules.Battle.Behaviors.BattleBehavior
---@field points table<number, UnityEngine.Vector3>
---@field grid AStar.Grid
---@field mainHero Game.Modules.Battle.Items.MainHero
local World = {}

World.battleSubScene = nil
World.battleBehavior = nil
World.points = nil

function World.EnterScene(sceneInfo, callback)
    World.mdr:EnterScene(sceneInfo, callback)
end

return World