---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2020-06-14-20:34:17
---

local BaseMediator = require("Game.Core.Ioc.BaseMediator")
---@class Game.Modules.Item.View.ItemBagMdr : Game.Core.Ioc.BaseMediator
---@field itemModel Game.Modules.Item.Model.ItemModel
---@field itemService Game.Modules.Item.Service.ItemService
local ItemBagMdr = class("Game.Modules.Item.View.ItemBagMdr",BaseMediator)

function ItemBagMdr:OnInit()
    
end

return ItemBagMdr
