---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2018-08-14-00:07:19
---


local BaseService = require("Game.Core.Ioc.BaseService")
---@class Game.Modules.Role.Service.RoleService : Game.Core.Ioc.BaseService
---@field roomModel Game.Modules.Room.Model.RoomModel
local RoleService = class("RoleService",BaseService)
local RoleVo = require("Game.Modules.Role.Vo.RoleVo")

function RoleService:Ctor()

end


return RoleService
