---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2020/4/18 23:10
--- 标准的表现
---

local BattleItemEvents = require("Game.Modules.Battle.Events.BattleItemEvents")
local PerformanceBase = require("Game.Modules.Battle.Performances.PerformanceBase")
---@class Game.Modules.Battle.Performances.Standard : Game.Modules.Battle.Performances.PerformanceBase
---@field New fun(avatar: Game.Modules.World.Items.BattleUnit):Game.Modules.Battle.Performances.Standard
---@field accountContextList table<number, Game.Modules.World.Contexts.AccountContext>
---@field accounts table<number, AccountInfo>
---@field accountCount number
---@field animCount number
local Standard = class("Game.Modules.Battle.Performances.Standard", PerformanceBase)

function Standard:Ctor(battleUnit, performanceInfo)
    Standard.super.Ctor(self, battleUnit, performanceInfo)
    self.sequenceOver = false
    self.accountContextList = {}
    self.accountCount = 0
    self.animCount = 0
end

---@param sequence DG.Tweening.Sequence
function Standard:OnBeginPerformance(sequence)
    Standard.super.OnBeginPerformance(self, sequence)

    self.skillVo = self.args[1] ---@type Game.Modules.Battle.Vo.SkillVo

    self:StartCoroutine(function()
        self.accounts = self.performanceInfo.accounts
        self:OnProcessStart()
        for i = 1, self.performanceInfo.times do
            self:Process()
            coroutine.wait(self.performanceInfo.interval / self.battleUnit.context.battleSpeed)
        end
        while self.accountCount < self.performanceInfo.times * #self.accounts do
            coroutine.step(1)
        end
        self:OnAllAccountEnd()
        while self.animCount < self.performanceInfo.times do
            coroutine.step(1)
        end
        self:OnProcessEnd()
        self.sequenceOver = true

    end)
    return true
end

--开始
function Standard:OnProcessStart()

end

function Standard:Process()
    if self.performanceInfo.accountType == AccountType.Single then
        --self.battleUnit:PlayIdle()
        self.battleUnit.accountCtrl:AccountProgress(self.performanceInfo.animInfo,function()
            for i = 1, #self.accounts do
                self:DoAccount(self.accounts[i])
            end
        end)
    else
        ---@param account AccountInfo
        self.battleUnit.accountCtrl:MultiAccountProgress(self.performanceInfo.animInfo, self.accounts, function(account)
            self:DoAccount(account)
        end)
    end
    self.battleUnit.animCtrl:PlayAnimInfo(self.performanceInfo.animInfo,Handler.New(function()
        self.animCount = self.animCount + 1
    end))
end


---@param account AccountInfo
function Standard:DoAccount(account)
    self.battleUnit.behavior:OnAttackAccount(account)
    self.accountCount = self.accountCount + 1
end

function Standard:OnAllAccountEnd()
    self.battleUnit.behavior:OnAttackAccountEnd()
end

function Standard:OnProcessEnd()

end

--重写阻塞函数
---@param sequence DG.Tweening.Sequence
function Standard:OnWaitPerformance(sequence)
    --等待开始阶段结束
    while not self.sequenceOver do
        coroutine.step(1)
    end
end

function Standard:Dispose()
    Standard.super.Dispose(self)
end

return Standard