---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2020-04-12-18:20:24
---

local BaseVo = require("Game.Core.BaseVo")
---@class Game.Modules.World.Vo.MonsterVo : Game.Core.BaseVo
---@field New fun():Game.Modules.World.Vo.MonsterVo
local MonsterVo = class("Game.Modules.World.Vo.MonsterVo",BaseVo)

function MonsterVo:Ctor()
    
end

return MonsterVo
