---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2020-04-12-20:26:05
---

local PoolObject = require("Game.Modules.Common.Pools.PoolObject")
---@class Game.Modules.World.Vo.SceneUnitVo : Game.Modules.Common.Pools.PoolObject
---@field New fun():Game.Modules.World.Vo.SceneUnitVo
---@field sid number
local SceneUnitVo = class("Game.Modules.World.Vo.SceneUnitVo", PoolObject)

local S_ID = 0

function SceneUnitVo:Ctor()
    
end

function SceneUnitVo:__sid()
    S_ID = S_ID + 1
    return S_ID
end

return SceneUnitVo
