---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2020-04-10-22:53:41
---

local BaseService = require("Game.Core.Ioc.BaseService")
---@class Game.Modules.Lobby.Service.LobbyService : Game.Core.Ioc.BaseService
---@field lobbyModel Game.Modules.Lobby.Model.LobbyModel
local LobbyService = class("Game.Modules.Lobby.Service.LobbyService",BaseService)

function LobbyService:Ctor()
    
end

return LobbyService
