---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2020-06-14-20:33:53
---

local BaseModel = require("Game.Core.Ioc.BaseModel")
---@class Game.Modules.Item.Model.ItemModel : Game.Core.Ioc.BaseModel
---@field itemService Game.Modules.Item.Service.ItemService
---@field itemList List | table<number, Game.Modules.Item.Vo.ItemVo>
local ItemModel = class("ItemModel",BaseModel)

function ItemModel:Ctor()
    
end

return ItemModel
