---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2020-04-12-21:40:27
---

local BaseService = require("Game.Core.Ioc.BaseService")
---@class Game.Modules.Player.Service.PlayerService : Game.Core.Ioc.BaseService
---@field playerModel Game.Modules.Player.Model.PlayerModel
local PlayerService = class("Game.Modules.Player.Service.PlayerService",BaseService)

function PlayerService:Ctor()
    
end

return PlayerService
