---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2018/6/10 20:56
---


-- --------------- [ 支撑系统定义 ] --------------- --
--- DOTween
---@class DOTween : DG.Tweening.DOTween
DOTween = DG.Tweening.DOTween
DOTween_Enum = {
    ---@type DG.Tweening.AutoPlay
    AutoPlay = DG.Tweening.AutoPlay,
    ---@type DG.Tweening.AxisConstraint
    AxisConstraint = DG.Tweening.AxisConstraint,
    ---@type DG.Tweening.Ease
    Ease = DG.Tweening.Ease,
    ---@type DG.Tweening.LogBehaviour
    LogBehaviour = DG.Tweening.LogBehaviour,
    ---@type DG.Tweening.LoopType
    LoopType = DG.Tweening.LoopType,
    ---@type DG.Tweening.PathMode
    PathMode = DG.Tweening.PathMode,
    ---@type DG.Tweening.PathType
    PathType = DG.Tweening.PathType,
    ---@type DG.Tweening.RotateMode
    RotateMode = DG.Tweening.RotateMode,
    ---@type DG.Tweening.ScrambleMode
    ScrambleMode = DG.Tweening.ScrambleMode,
    ---@type DG.Tweening.TweenType
    TweenType = DG.Tweening.TweenType,
    ---@type DG.Tweening.UpdateType
    UpdateType = DG.Tweening.UpdateType,
}
DOTween.defaultEaseType = DOTween_Enum.Ease.Linear

Hud = Framework.Hud

Screen = UnityEngine.Screen

--- Lua Framework
edp = EventDispatcher.New() --全局事件派发器
ListViewEvent = require("Betel.UI.ListViewEvent")
BaseList = require("Betel.UI.BaseList")
--ListExtend = require("Module.Common.View.ListExtend") ---@type Module.Common.View.ListExtend
ListItemRenderer = require("Betel.UI.ListItemRenderer")

--- Global Events
WorldEvents = require("Game.Modules.World.Events.WorldEvents")
PointerEvent = require("Game.Events.PointerEvent")
DragDropEvent = require("Game.Events.DragDropEvent")
ViewEvents = require("Game.Events.ViewEvents")

--- FastBehavior
--StateAction = FastBehavior.StateAction
StateMachine = FastBehavior.StateMachine
--StateNode = FastBehavior.StateNode
FastLuaBehavior = FastBehavior.FastLuaBehavior
smMgr = FastBehavior.StateMachineManager.GetInstance() --状态机
smMgr:Init()
smMgr.StateActionTimeout = 100

---Utils
StringUtil = require("Game.Core.Utils.StringUtil")
ObjectUtil = require("Game.Core.Utils.ObjectUtil")
Tools3D = require("Game.Core.Utils.Tools3D")
UITools = require("Game.Core.Utils.UITools")
Timer = require("Game.Core.Utils.Timer")
TimeUtil = require("Game.Core.Utils.TimeUtil")

--- UI Utils
Alert = require("Game.Modules.Common.View.Alert")
Tips = require("Game.Modules.Common.View.Tips")
NetModal = require("Game.Modules.Common.View.NetModal")
ImageHelper = require("Game.Modules.Common.View.ImageHelper")

---Global
World = require("Game.Modules.World.World")
FRAME_TIME = 1 / Application.targetFrameRate

-- [声音系统]
--SoundPlayer = require("Game.Modules.Common.Sound.SoundPlayer").New()
--SoundConfig = require("Data.SoundConfig")
--SoundPlayer:Init()
--

--

-- --------------- [ 项目自定义 ] --------------- --

---Config
--Config = require("Data.Config")
--GameConst = require("Data.GameConst")
--StrategyConsts = require("Module.World.Behaviors.Strategy.StrategyConsts")
--BehaviorUtils = require("Module.World.Behaviors.BehaviorUtils")
--Language = require("Data.Languages." .. Config.language)

---Static Data
--SkillConfig         = require("Data.SkillConfig")
--AvatarConfig        = require("Data.AvatarConfig")
--EffectConfig        = require("Data.EffectConfig")
--AvatarUIConfig      = require("Data.AvatarUIConfig")
--PlotConfig          = require("Data.PlotConfig")
--BattleConfig        = require("Data.BattleConfig")
--GridBattleConfig    = require("Data.GridBattleConfig")
--CheckPointConfig    = require("Data.CheckPointConfig")
--CameraShakeConfig   = require("Data.CameraShakeConfig")
--BufferConfig        = require("Data.BufferConfig")
--PerformanceConfig   = require("Data.PerformanceConfig")
--StateConfig         = require("Data.StateConfig")
--CardConfig          = require("Data.CardConfig")
--ItemConfig          = require("Data.ItemConfig")
--AdventureEventConfig = require("Data.AdventureEventConfig")
--AdventureEventAfterEventConfig = require("Data.AdventureEventAfterEventConfig")
--PathConfig        = require("Data.PathConfig")
--StageConfig        = require("Data.StageConfig")
--ChapterConfig        = require("Data.ChapterConfig")

---Utils
--BattleUtils = require("Module.Battle.Utils.BattleUtils")
--Stage.loadingSceneClass = require("Module.Loading.View.LoadingScene")
--Convert = require("Module.Common.Convert")
--Layers = require("Module.Common.Layers")
--World = require("Module.World.World")
--Convert = require("Module.Common.Convert")
--Math3D = require("Module.Common.Math3D")
--File = require("Module.Common.File")
--Tool = require("Module.Common.Tool")
--TimeConvert = require("Module.Common.TimeConvert")
--Alert = require("Module.Common.Alert")
--PoolFactory = require("Module.Common.Pools.PoolFactory")
--BezierUtils = require("Module.Common.BezierUtils")
--Plot = require("Module.Plot.Scripts.Plot")
--GuideLine = require("Module.Common.Effect.GuideLine")
--PerformancePlayer = require("Module.World.Performances.PerformancePlayer")

---3rd
--AStarUtils = require("Module.Common.AStarUtils")
--MoveUtils = require("Module.Common.MoveUtils")
--GridUtils = require("Module.Common.GridUtils")
--Live2D = require("live2d.Live2D")
--Live2D.init();


---对象池
--PoolVoProxy     = require("Module.Common.Pools.PoolVoProxy")
--HeroVoPool      = PoolVoProxy.New("Module.World.Vo.HeroVo")
--MonsterVoPool   = PoolVoProxy.New("Module.World.Vo.MonsterVo")
--SkillVoPool     = PoolVoProxy.New("Module.World.Vo.SkillVo")
--AttributePool    = PoolVoProxy.New("Module.World.Vo.Attribute")
--Icon = require("Module.Common.Icon.Icon")
--Star = require("Module.Common.Star.Star")
--WorldIcon = require("Module.Common.Icon.WorldIcon")