---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2018/7/13 1:28
--- 全局常量
---

---@class UILayer
UILayer = {}
UILayer.scene = "scene"
UILayer.bg = "bg"
UILayer.bottom = "bottom"
UILayer.depth = "depth"
UILayer.alert = "alert"
UILayer.guide = "guide"
UILayer.top = "top"

ServerName = {}
ServerName.AccountServer = "AccountServer"
ServerName.GateServer = "GateServer"
ServerName.GameServer = "GameServer"

---===============
--- 常量
---===============
--目标帧率
Application.targetFrameRate = 60
FrameRate = Application.targetFrameRate
--目标帧间隔时间
FRAME_TIME = 1 / FrameRate

---===============
--- 枚举
---===============

--View 状态
ViewStatus = {}
ViewStatus.Loading      = "Loading"
ViewStatus.Loaded       = "Loaded"
ViewStatus.Unloading    = "Unloading"
ViewStatus.Unloaded     = "Unloaded"

GameName =
{
    Hong_Jian = "Hong_Jian"
}

GameMode =
{
    Hong_Jian = "1vs1"
}
---@class RoomRoleState 玩家在房间中的状态
RoomRoleState =
{
    UnReady         = "UnReady",
    Ready           = "Ready",
    Loading         = "Loading",
    LoadComplete    = "LoadComplete",
    Offline         = "Offline",
    Reconnect       = "Reconnect",
    PlayingGame     = "PlayingGame",
    Automatic       = "Automatic"
}

--桌子的位置(相对玩家,上北下南,左西右东)
DeskPos = {}
DeskPos.South = "South"
DeskPos.North = "North"
DeskPos.West = "West"
DeskPos.East = "East"