---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2018/7/13 1:28
--- 全局系统常量
---

---@class UILayer
UILayer =
{
    -- 场景图层
    LAYER_SCENE = "scene", -- 场景层
    LAYER_EXTEND_UI = "uiExtendLayer", -- UI可伸缩层
    LAYER_MOVE_UI = "uiMoveLayer", -- UI可移动层
    LAYER_DEPYH_UI = "depth", -- UI深度排序层
    LAYER_WINDOW = "windowLayer", -- 窗口层
    LAYER_UI_TOP = "uiTopLayer", -- 顶级UI层
    LAYER_ALERT = "alert", -- 提示层
    LAYER_GUIDE = "guide", -- 引导层
    LAYER_TOP = "top", -- 顶级层
}

ServerName = {}
ServerName.AccountServer = "AccountServer"
ServerName.GateServer = "GateServer"
ServerName.GameServer = "GameServer"

---===============
--- 常量
---===============
--目标帧率
Application.targetFrameRate = 60
FrameRate = Application.targetFrameRate
--目标帧间隔时间
FRAME_TIME = 1 / FrameRate

---===============
--- 枚举
---===============

--View 状态
---@class ViewStatus
ViewStatus = {}
ViewStatus.Loading      = "Loading"
ViewStatus.Loaded       = "Loaded"
ViewStatus.Unloading    = "Unloading"
ViewStatus.Unloaded     = "Unloaded"
