---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2018/6/11 0:23
---


require "Game.Core.Define"
require "Game.Core.Functions"
require "Game.Core.Components"
require "Game.Core.GlobalConsts"


log("Game.Core define has all require")