---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2020-06-20-21:29:18
---

local BaseVo = require("Game.Core.BaseVo")
---@class Game.Modules.CheckPoint.Vo.ChapterVo : Game.Core.BaseVo
---@field New fun():Game.Modules.CheckPoint.Vo.ChapterVo
local ChapterVo = class("Game.Modules.CheckPoint.Vo.ChapterVo",BaseVo)

function ChapterVo:Ctor()
    
end

return ChapterVo
