---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2020-07-21-23:18:01
---

local BaseVo = require("Game.Core.BaseVo")
---@class Game.Modules.CheckPoint.Vo.ChenkPointReportVo : Game.Core.BaseVo
---@field New fun():Game.Modules.CheckPoint.Vo.ChenkPointReportVo
local ChenkPointReportVo = class("Game.Modules.CheckPoint.Vo.ChenkPointReportVo",BaseVo)

function ChenkPointReportVo:Ctor()
    
end

return ChenkPointReportVo
