---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2019-05-18-23:23:12
---

local BaseService = require("Game.Core.Ioc.BaseService")
---@class Game.Modules.Battle.Service.BattleService : Game.Core.Ioc.BaseService
---@field battleModel Game.Modules.Battle.Model.BattleModel
local BattleService = class("BattleService",BaseService)

function BattleService:Ctor()
    
end

return BattleService
