---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2020-06-19-23:48:14
---

local BaseModel = require("Game.Core.Ioc.BaseModel")
---@class Game.Modules.CheckPoint.Model.CheckPointModel : Game.Core.Ioc.BaseModel
---@field checkPointService Game.Modules.CheckPoint.Service.CheckPointService
---@field currChapter Game.Modules.CheckPoint.Vo.ChapterVo
---@field currSection Game.Modules.CheckPoint.Vo.SectionVo
local CheckPointModel = class("CheckPointModel",BaseModel)

function CheckPointModel:Ctor()

end

return CheckPointModel
