---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2020-06-19-23:48:17
---

local ChapterVo = require("Game.Modules.CheckPoint.Vo.ChapterVo")
local BaseService = require("Game.Core.Ioc.BaseService")
---@class Game.Modules.CheckPoint.Service.CheckPointService : Game.Core.Ioc.BaseService
---@field checkPointModel Game.Modules.CheckPoint.Model.CheckPointModel
local CheckPointService = class("CheckPointService",BaseService)

function CheckPointService:Ctor()
    
end

---@param roleId string
---@param callback fun()
function CheckPointService:getChapterInfo(roleId, chapterId, callback)
    self:HttpRequest(Action.ChapterInfo, {roleId, chapterId}, function(data)
        local chapterVo = ChapterVo.New(data.chapterInfo)
        self.checkPointModel.currChapter = chapterVo
        invoke(callback, data)
    end)
end

return CheckPointService
